### ISSUE TITLE
Refreshing Subscriptions

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#102]
We need to support subscription refreshes to ensure liveness and also signal explicit consent. The latter will be needed from security perspective and also protecting relay from resource exhaustions.
The protocol should also recommend what the Relays should do in such cases

**Comment by vasilvv** [comment]
Consent freshness can be provided via QUIC itself, we just don't do that by default.  See w3c/webtransport#174 for some discussion we had regarding consent freshness in WebTransport (the short answer is that the server can send a PATH_CHALLENGE regularly).

Is there any specific reason you want this to be done at a subscription level?

**Comment by suhasHere** [comment]
Thanks for the reference victor .. This is an explicit request from the client telling to Relay of the continuiing interest for a given set of subscriptions and to avoid Relays from needing to hold onto the subscription.

**Comment by afrind** [comment]
It makes sense that a relay would need to reap upstream subscriptions when all the downstream subscribers are gone.  Is it better to automatically expire subscriptions and require the client to refresh, or automatically extend subscriptions and require the client to unsubscribe, and terminate all active subscriptions when the underlying WebTransport session or  QUIC connection closes?

What are the pros and cons of each approach?  Should the base protocol support both modes?

**Comment by suhasHere** [comment]
> and terminate all active subscriptions when the underlying WebTransport session or QUIC connection closes?

The control stream PR proposes a solution for this. Subscriptions of one or more tracks, are tied to a control stream and when that streams closes, it closes all the linked media transfer state.

**Comment by suhasHere** [comment]
> Is it better to automatically expire subscriptions and require the client to refresh

Relays always have a choice to terminate any subscription if the local policy decides. In those cases, if a client is still interested , it should have to renew/refresh the subscription if it has not already done. It does cause media disruptions at the clients to be torn down its media and having a mechanism to renew will be useful.

It is good security feature for relays to be told I am still interested in receiving media so to prevent DOS of relay's resources for maintaining the needed state.

**Comment by afrind** [comment]
As an individual:

Continual subscription sounds expensive to me, so I'd prefer that not be the only mode.  I think there are tradeoffs to explicit cancellation client vs implicit cancellation.  If the publisher controls the implicit subscription timeout and they can set it to t = ~infinity it's kind of the same thing.

**Comment by suhasHere** [comment]
> If the publisher controls the implicit subscription timeout and they can set it to t = ~infinity it's kind of the same thing.

I was not suggesting publisher control the subscription timeout.  Subscriptions renewal periods are paced apart, say 5-10 seconds and depends on the application. 
Also no matter what is set, Relays can overwrite if they see those values are meaningless.  
Should we make this a MUST option or Not, I am fine to go either way as long as the protocol supports that behavior. Since it will be important from security perspective.

**Comment by kixelated** [comment]
We don't need to refresh subscriptions.

**QUIC has an idle timeout**. This is meant to detect severed connections, even if no media is being transferred. You could set it as low as 5-10s to get the same user experience as your periodic subscriptions, but without any involvement from the application.

---

**QUIC has a congestion window**. The sender will stop sending packets if they're not being acknowledged. Here's what it looks like when the connection is severed without a  CONNECTION_CLOSE:
 
<img width="395" alt="Screen Shot 2023-03-17 at 9 55 39 AM" src="https://user-images.githubusercontent.com/432854/225969339-c75aeb0d-f32b-4048-9734-33d545dea28d.png">

The sender keeping sending media (green) for 800ms before hitting the congestion window (purple), then it will no longer send any more media until it receives an acknowledgement. This is far more responsive than an idle timeout, which is still used to eventually terminate the connection.

Note that QUIC datagrams are congestion controlled and are subject to this congestion window.

---

**QUIC streams have flow control**. The QUIC library will only increase MAX_DATA when the application reads from streams. That means even if there's a bug in the application, like a fatal error causing it to hang, then there will still be back-pressure and the sender will be blocked. This is even more resilient than a periodic refresh, especially because that code would likely be run in it's own thread.

Note that QUIC datagrams are NOT flow controlled. Maybe your periodic subscription stems from this difference?

**Comment by afrind** [comment]
Leveraging QUIC transport features seems like it works to help the relays reap dead subscribers when they step into an elevator.  Are there other scenarios that need coverage like:

1.  We kicked Bob out of the meeting so he's no longer allowed to get any tracks.
2. You stopped paying for your subscription to this streaming service so we're going to stop serving this content 

In HTTP CDNs this kind of reauthorization tends to be slow (eg: the URLs have an expiration time signed in).  Is that a problem we need to solve better in moq?

**Comment by kixelated** [comment]
Reneging authorization is certainly a reason to require refreshing subscriptions. @suhasHere I think this is the problem you're trying to solve, especially since you have an auth token in the SUBSCRIBE messge. If so, could you rename the issue so it focuses on the problem, and not a possible solution?

---

The current draft punts authorization to the WebTransport CONNECT. There's no way to refresh that request, so the relay would just terminate the connection with an unauthorized error code.

But how does a CDN know when a session is authorized or no longer authorized? It's undefined in the current draft and up to the application.

This is also how HTTP CDNs work. There may be millions of viewers connected to a CDN, but they all deduplicates into a single request to the origin. The CDN is responsible for authentication, usually just because the URL is unguessable but sometimes via a signed token.

We absolutely need the ability to fan out authentication in order to scale. The origin is not capable of handing millions of requests per second, especially if authentication is performed via a subscription every few seconds. And we still need some form of authentication in order to connect to the CDN edge in the first place, especially if media is pushed sans subscription in order to reduce TTV.

My suggestion would be an optional standard. Some form of token that you provide to the CDN as part of the WebTransport CONNECT, which has an expiration time and some mechanism for the CDN to verify/refresh it. The authentication service would be decoupled from the origin. I'm sure some standard like this already exists but I'm not aware of the space, @wilaw do you know?

**Comment by suhasHere** [comment]
All the renewal option is telling " I am still interested in the subscription " as an explicit signal from the application to the Relays. This is not tied to the transport options, but those options can help tear down stale subscriptions. The same is with relay local policies. 

On how the subscriptions renewal gets authorized - that's a tangent and we can solve it as separate issue.

**Comment by kixelated** [comment]
Sorry, I got too excited and leapt to conclusions.

@suhasHere what problem are you solving? Why would an unsubscribe message be insufficient?

**Comment by fluffy** [comment]
One way or another we have to meet the requirement that the sever can know when to clean up state. If that is done purely by the QUIC connection going away, well  I guess that could work as long as it has appropriate keep alive but it would be nice to make this fairly easy for architectures where the load balancer in front of the server terminates the QUIC, the TLS. Be good to see some explicit proposal for how this work on the raw QUIC cases.

**Comment by wilaw** [comment]
> we have to meet the requirement that the sever can know when to clean up state.

If we follow the architectural precept that any node only publishes in response to a subscribe and we have an "unsubscribe" message, then we have a simple system that would clean up automatically

If an edge relay ends up having no subscribers for a track, either due to all subscribers sending it an unsubscribe (clean) or their connection timing out or dropping, then the edge relay would send an unsubscribe to its parent. This process would work its way up the tree until eventually the publisher would stop sending content because it had no subscribers.

**Comment by afrind** [comment]
See also #132 about adding explicit unsubscribe.

**Comment by afrind** [comment]
@suhasHere The current draft allows for `expires` in SUBSCRIBE OK.  We're missing UNSUBSCRIBE but there's a separate issue tracking that.  Is this sufficient to close?

**Comment by suhasHere** [comment]
@afrind yes, we have tackle unsubscribe in #132
