### ISSUE TITLE
Track bundle definition need not be same as Catalog

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#103]
Current spec as "The track bundle contains a catalog indicating the available tracks."

This seems very constraining. A catalog lists multiple tracks and a track bundle groups the tracks based on the prioritzation requirement. 

Linking catalog as 1:1 mapping to track bundle, will cause all the tracks in a catalog needs to be used OR one should send multiple catalogs based on the prioritization requirements. I feel we are again trying to force an application behavior, which should be avoided that we are building toolset for various applications

**Comment by afrind** [comment]
As an individual:

> Linking catalog as 1:1 mapping to track bundle, will cause all the tracks in a catalog needs to be used 

As I read the draft, a track bundle is defined as the set of tracks available at a given WebTransport URL, and the catalog contains (in some way) the ids of those tracks.  I didn't read that all tracks defined in a catalog MUST be subscribed to, the application can subscribe to a subset.  Placing tracks in the same bundle will allow the publisher to prioritize the tracks in the bundle relative to each other.

> OR one should send multiple catalogs based on the prioritization requirements.

Since tracks prioritized against each other belong in the same catalog, the only reason for multiple catalogs is groups of tracks that are not related.  I think an application using this draft would accomplish this by making a WebTransport session to each independent track-bundle URL (maybe over the same QUIC connection), each would have an independent catalog.  Is this design problematic and if so, can you explain why?

As Chair:

> I feel we are again trying to force an application behavior, which should be avoided that we are building toolset for various applications

I think everyone is in agreement that we are trying to build a toolset to support multiple applications.  Rather than make a generic statement like "we are again trying to force an application behavior", please give an example of an application that cannot be built with any given proposed design.

**Comment by suhasHere** [comment]
@afrind  may be my read of this statement is wrong "The track bundle contains a catalog indicating the available tracks." This means that catalog is scoped to a track bundle  and not that tracks in the bundle coming from a catalog. They are 2 different requirements ..

What is your read of that statement ?

**Comment by afrind** [comment]
As an individual:

I read track-bundle as a hop-by-hop entity rather than an end-to-end entity.  A relay could be receiving N track bundles, mixing up the tracks between them and publishing M different track bundles to its subscribers.  Each track bundle has a catalog that identifies the available streams in the bundle, so in that example, the relay is creating the new downstream catalogs.  The set of available tracks in a bundle can change over time, via updates to the catalog.

Or another way: WebTransport Session = Track Bundle = 1 Catalog of available tracks

So yes, I think both options are available: one where a receiver subscribes to all tracks in a catalog, and one where a receiver subscribes to a subset, and can open multiple WebTransport sessions to the same URL with different subsets.

What the draft doesn't define today is an entity containing a "composition" -- one that contains tracks from different WebTransport URLs.  I think about such an entity like an HTML page that has links to resources from anywhere.  It's an important tool, but not one defined by HTTP.  In my individual opinion, this is out of scope for the base protocol.

**Comment by suhasHere** [comment]
> Each track bundle has a catalog that identifies the available streams in the bundle

catalog is a larger container of tracks and bundles are groups of tracks which happened to mapped to WT when WT is the transport.  It shouldn't matter if it is composition or emissions, it will help if we think of concepts as
- catalogs have list of tracks
- catalogs are retrieved from a moq session url ( can be emission or composition)
- clients group subset of tracks listed in the catalog as  bundles

I am not sure the gains of having a catalog per bundle ..

**Comment by kixelated** [comment]
First off, I think it's a great idea to move catalog into its own track (#66). That would enable you to have multiple catalogs in the same track bundle and would make consuming catalogs optional.

And I absolutely agree that applications should be able to distribute a catalog/composition out-of-band. But should it be mandatory to have a catalog in-band?

I resonate with @wilaw's comment: https://github.com/kixelated/warp-draft/issues/66#issuecomment-1415092508

> IMO the CATALOG message and its response should exist in the base protocol and be mandatory to implement on the part of the publisher and relays. For the client, its optional. The majority of clients would use it. Those that can receive the catalog out-of-band would not need to use it. I envisage CATALOGS not being static in the life of a stream. They should update when the mix of content being produced by the publisher changes (i.e a webex user suddenly starts sharing their desktop). To that end, even a client that starts with an out-of-band catalog would still want to SUBSCRIBE to CATALOG updates, so that it can be apprised of any future changes to the subscription IDs on offer. I can also imagine dynamic ad insertion opportunities being signaled by CATALOG changes. Additionally, a CATALOG update to say there is no more content being published would be a clean way to terminate a broadcast.

To add to that, it seems impossible to implement a generic endpoint like VLC/OBS/etc unless there is a required catalog track or message.

**Comment by hardie** [comment]
I think there are two different meanings of catalog in play here.  To use a
very old fashioned example, a department store catalog has a huge number of
available items, but no customer would ever get all of them in a single
order.  They make a selection and the list of things that they selected
could also be called a catalog (a catalog of the order, rather than of the
goods in the department store).

If I'm reading this correctly, everyone agrees that

WebTransport Session = Track Bundle

The question is whether the track bundle represents "The set of things
available for selection" (the standard English commercial meaning of
catalog)  or "An enumerated list of those things which are now in a single
priority domain" (aka, the tracks selected from the larger set).

With no particular hat on, I think the discussion among the participants
sounds like "enumerated list of those things now in a single priority
domain" is the right third term for Web Transport Session = Track Bundle =
X.   Whether X is called "catalog" or not seems to be the point of
disagreement.

I may have this wrong, of course, but that's what it looks like from my
perspective.

Ted

**Comment by kixelated** [comment]
Yeah exactly Ted. My thought is that:

A *catalog* describes a track bundle. "Here's a list of tracks available on the WebTransport session."

A *composition* describes multiple track bundles. "Here's a list of multiple tracks, which are available from separate WebTransport sessions."


There is absolutely room to combine the two into a single entity. It just gets a little awkward when catalog updates and 3rd party clients are thrown into the picture.

My proposal is catalog is part of the transport draft while composition is punted to the application or part of a separate draft.

**Comment by suhasHere** [comment]
Thanks Ted, keeping on building the elementary transport tools in mind , i was proposing the equation to be

"Web Transport Session = Track Bundle " and not add in catalog in that equation

Yes in some cases, a catalog = track bundle and that is fine as application implementation choice and transport need not enforce that relationship.

**Comment by afrind** [comment]
As an individual:

Maybe we need to drop the names for a minute and see if we can agree on concepts:

A *zibbermap* is a list of tracks sent by the publishing endpoint of a WebTransport session to the receiving endpoint.  The receiving endpoint can subscribe to 0 - all of these tracks *in this session*.  
It may not be exhaustive: an endpoint can try subscribing to a track ID in this session that it got out of band and that *might* work.
The *zibbermap* doesn't include any track IDs that *can't be subscribed to in this session*.  A list of track-IDs from several different WebTransport URLs is called a *wheeblist*.  A *zibbermap* can be thought of as a subset of a *wheeblist* where the WebTransport URLs of all track IDs match the current session's URL.  The reason for defining a specialized construct *zibbermap* is that it is highly relevant to the receiving endpoint, and it might be confusing to receive information about other tracks in other places.

**Comment by wilaw** [comment]
> If I'm reading this correctly, everyone agrees that WebTransport Session = Track Bundle

Perhaps I'm an outlier but in my reading there is not yet complete agreement on this point.  The direct consequence of this assumption is that MoQ Objects rely upon the WebTransport session they are transmitted within for their identification. Consider the case of a web conference vendor that can easily have 200,000 concurrent conference sessions, and a game streamer another 200,000. For a distribution vendor distributing both, every hop between every pair of intermediaries along the distribution path needs to establish 400,000 WebTransport connections in order to correctly relay using MoQ. These unique WebTransport sessions per end-user must be maintained all the way to the respective origins.

It’s not the number of WebTransport sessions that is necessarily concerning, it’s the rigid requirement that there is a 1:1 mapping between the content bundles (which are application defined)  and the transport (which is  network vendor maintained). What if the distribution vendor wants to shard these bundles across 1, or 1,000, or 100,000 WebTransport sessions for memory, performance or hardware requirements? Or they are not using WebTransport and only using Quic? They should have the flexibility to innovate in that regard, but to have to use 400,000  (in this example) for MoQ to work is a strict requirement and we should think that through carefully before mandating it. 

This inflexibility exists in return for the convenience of not putting sufficient information in the headers of each object to route them independently of the WebTransport or Quic sessions. 

An alternate approach is therefore to put enough information in each object header to make if “sufficiently unique” such that object can be transferred independently of the underlying Webtransport session and/or QUIC connection. This does not require a GUID in every object, but rather some lower level of uniqueness. The varint that is identifying the WebTransport session within the Quic connection could equally be placed in the object headers.

Various schemes for this have been proposed, along with the option for a vendor to implement a dictionary and header rewrite to reduce the bits across the wire within their network. It seems these should at least be considered as an equally viable and perhaps preferred solution to the WebTrans session == track-bundle requirement.

**Comment by suhasHere** [comment]
Will, if I may clarify, today bundle is defined per broadcast/emission IIUC. So that would make total WT ~= 200,000 conferences * number of emissions per conference .   I may have wrongly read the current draft and would love to get further clarification of my understanding.


Agree with Will that, Even though we don't mandate a relay behavior, we shouldn't be constraining the design choices. May be we can solve the prioritization across tracks/connections with priorities ??  Regardless, we need to explore the thinking here

**Comment by kixelated** [comment]
Let me explain on the ML. I'm writing the email about track bundles now.

**Comment by wilaw** [comment]
So thanks Luke for your ML description of track bundles. That cleared things up a bit. 

I'm on board with the simple but flexible construct that a "bundle" is a collection of tracks available under a single WebTransport session. This represents content generated under a consistent prioritization and orchestration domain. We need this because we can only guarantee relative stream prioritization within a WebTransport session and not between pooled WebTransport sessions. One of these tracks is called "catalog" and it describes the other tracks, providing for each the info the client will need for selection, subscription and initialization.

**Comment by fluffy** [comment]
I don't see why any of this is tied to a WebTrasport or what that would mean in the raw Quic case. 

I'm having a very hard time understanding if this bug is even still relevant given the Japan discussion. Could we close this bug and open one or more specific bugs that are get to heart of the issue.

**Comment by afrind** [comment]
@suhasHere are we good to close?  The track bundle name is gone from the spec.

**Comment by suhasHere** [comment]
@afrind  yes we can close this
