### ISSUE TITLE
Objects can be individually cached and served (A way to GET one or more objects)

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#111]
Some use-case like  catchup , go back to a given object for layer refresh or server the game state from a given object , and similar scenarios ,  would need a name to ask for the object. 
It would be good for the protocol to be able to subscribe to not just track and group, but also object.

**Comment by kixelated** [comment]
Can you elaborate on the use-case?

Resumption after a connection is severed makes sense. We need to solve that for both the contribution and distribution use-case. @vasilvv has some strong opinions here.

I don't quite understand the second use-case. Why would a consumer need to refetch a single object, but none of the objects it could depend on? It only makes sense when there's a hole in the cache, but why did that happen and how does the subscriber know about it?

**Comment by kixelated** [comment]
And to be clear, I also think we should have a GET equivalent, but I want to make sure I understand the ask.

**Comment by acbegen** [comment]
> It only makes sense when there's a hole in the group, but why did that happen and how does the subscriber know about it?

The encoder might have skipped some frames due to input loss or another issue, but maybe they are available from a redundant encoder and you would like to "fill the gaps"? The subscriber only sees the gap, it does not need to know the dependency structure.

**Comment by fluffy** [comment]
Two uses cases I am thinking, both on distribution side:

Use case A: 
* client join a session that is in progress and wants to join Track A. The client wants to start playing before the next the GOP starts so it subscribes to Track A with the most recent group and wants to get *all* the objects in the group. 

Use case B: 
* client is watching Track A  and has received all the objects up to group 123 object 45 and looses wifi and switched to 5G. At this point it forms a new subscription to Track A but it wants to start at group 123 object 46 because it already has the stuff before that. If it had to wait to received all the stuff in group 123 over again, it would add delay as it switched networks. 

There are some more uses from scalable codecs but if we can solve the above two cases, we will probably solve the toher uses cases as well.

**Comment by fluffy** [comment]
I think the solution to this is simply that the Subscribe can have some sort of flag that indicates if the clients wants just future objects, or if wants to catch up on all the objects in the current group, or wants all the objects after some particular objectID

**Comment by ianswett** [comment]
Will suggested solving this as part of #245 and have both a start group and end group.
