### ISSUE TITLE
CDN: Deduplication

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#118]
**Problem**: A CDN is only works due to deduplication. In the HTTP world, an edge node receives millions of requests, with different URLs and headers, and is able to figure out how to deduplicate them into far fewer upstream requests. This reduces the work for each upstream hop making it feasible for individual origin hosts to effectively serve millions of requests.

In the MoQ world, we need to deduplicate subscriptions. If there are 100 viewers connected to a CDN edge and SUBSCRIBE for the same broadcast, then ideally that would translate into a single SUBSCRIBE call upstream.

**Comment by kixelated** [comment]
In order to do this, the edge relay needs enough information to know when subscriptions can be deduplicated. In the HTTP world, this is handled by bespoke business logic (based on the URL and some headers).

As part of that process, the edge relay needs to deduplicate/remove any user-specific information. Importantly, that includes authentication; a relay edge must be able to authenticate per-session tokens in order to deduplicate. Otherwise it could serve unauthorized data from the cache.

**Comment by kixelated** [comment]
My proposal is to adopt the existing HTTP world. As part of signing up for a CDN, the application configures the business logic required to both authorize, remap, and deduplicate incoming subscriptions. Maybe we could standardize something but I figure that's been tried already in the HTTP world.

**Comment by fluffy** [comment]
HTTP was not designed for caches ( they were added much later ) which results in this being a bit crazy - luckily we can design this right from the start. 

From a data model point of view we are asking who can receive a copy of a given object because tis what we transfer or who is allowed to publish a give object. Each track has a globally unique name, and the object is inside a group inside that track. I think this is why it is critical we authorize both publish and subscribe at a track level of granularity. We might also need to authorize at the connect level but I don't think that has the level of granularity to allow a given client to be able to subscribe to a track but not be allowed to publish to that same track.  

I agree on de-duplication. I think the track name + groupID + objectID gives a unique name of the object that allows the CDN to both cache and deduplicated. 

All that said, I think I come to the same conclusion as you that the client needs to include a token that the CDN can validate and that the token can be tied to the track name. I think we can use the same token as are often used in HTTP and we don't even need to get into what the tokens are, just that the transport caries them and the CDN uses to validate.

**Comment by kixelated** [comment]
Closing because there's no action item.
