### ISSUE TITLE
Proposal: ANNOUNCE catalog tracks

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#150]
### Current
The publisher sends a CATALOG message is used to announce valid track names and an init payload. The init payload contains metadata used by the application to select acceptable tracks.

### Problems
- #66 The CATALOG message is specific to media, and should be made more generic to support other use-cases.
- No support for multiple CATALOGs, including multiple formats or versions.
- No support for CATALOG updates.

### Proposed
- Create a track for each catalog.
  - All track contents are delegated to a separate draft, such as: https://github.com/wilaw/MoQ
  - Note that the catalog may initialization information, so it may be required.
- Create a registry of track formats.
- The publisher(s) ANNOUNCEs the available track name and format pairs.
  - Sent on the SETUP control stream with #138 to avoid a round trip.
- The consumer(s) SUBSCRIBEs to the catalog track to learn more about track metadata.
  - An endpoint may subscribe to all tracks to avoid this round trip.
  - An application may negotiate out-of-bound to skip this round trip.
- The consumer(s) SUBSCRIBEs to individual tracks.

### Pros
- Tracks are used for catalog transfer and updates.
- Multiple catalogs formats can be offered simultaneously, describing the same data tracks.
- The catalog format may be increased for major versions. (ex. moq v1 and moq v2)
- The catalog is not required to determine the track format.
- The transport protocol is media-agnostic.
- Makes catalog transfer optional.

### Cons
- Requires a track format registry.
- Leaks the format of each track.

### Examples
```
contribution-generic (client -> server):
-> SETUP
-> ANNOUNCE (name=catalog format=cmaf-init), (name=video format=cmaf-data), (name=audio format=cmaf-data)
<- SETUP
<- SUBSCRIBE id=1 name=catalog
-> OBJECT id=1
<- SUBSCRIBE id=2 name=video
<- SUBSCRIBE id=3 name=audio
-> OBJECT id=2
-> OBJECT id=3
(3 rtts)
```

```
contribution-all (client -> server):
-> SETUP
-> ANNOUNCE (name=catalog format=cmaf-init), (name=video format=cmaf-data), (name=audio format=cmaf-data)
<- SETUP
<- SUBSCRIBE id=1 name=catalog
<- SUBSCRIBE id=2 name=video
<- SUBSCRIBE id=3 name=audio
-> OBJECT id=1
-> OBJECT id=2
-> OBJECT id=3
(1.5 rtts)
```

```
distribution-generic (client -> server):
-> SETUP
<- SETUP
<- ANNOUNCE (name=catalog format=cmaf-init), (name=video format=cmaf-data), (name=audio format=cmaf-data)
-> SUBSCRIBE id=1 name=catalog
<- OBJECT id=1
-> SUBSCRIBE id=2 name=video
-> SUBSCRIBE id=3 name=audio
<- OBJECT id=2
<- OBJECT id=3
(3 rtts)
```

```
distribution-all (client -> server):
-> SETUP
<- SETUP
<- ANNOUNCE (name=catalog format=cmaf-init), (name=video format=cmaf-data), (name=audio format=cmaf-data)
-> SUBSCRIBE id=1 name=catalog
-> SUBSCRIBE id=2 name=video
-> SUBSCRIBE id=3 name=audio
<- OBJECT id=1
<- OBJECT id=2
<- OBJECT id=3
(2 rtts)
```

**Comment by wilaw** [comment]
@kixelated  - thanks for stubbing this out. I find that the ANNOUNCE messages proposed here are almost exact duplicates of the contents of the catalog. The purpose of the catalog is 3-fold:
1. To list the track names that are available for subscription as part of the content "bundle"
2. To describe all the attributes of the track that the client may need for track selection 
3. To provide initialization data for each track. 

By having to ANNOUNCE each track, the client is duplicating what is already inside the catalog. The catalog IS the announcement of what the server is making available for subscription. 

This proposal also assumes that "formats" can be scoped to "tracks". This works in the overly simplistic assumption that one "format" differs from another only in the container or codec that is used and that the tracks can be consumed independently of one another. In reality, tracks may be tied to one another. A current example would be SVC layers. A more advanced example would 3D environments where 10 tracks, in a hierarchical tree, must be consumed in order to receive the correct spatial vertex and shader information. We cannot describe the complexity of all of that, and the relationships, in ever expanding key-value pairs in ANNOUNCE messages. The role of the catalog is to abstract away all that complexity of what's in tracks and how tracks are related to one another and what tracks constitute the "bundle". 

I would propose an alternate solution that accommodates the complexity described above and that allows multiple concurrent streaming formats to be offered by the same publisher, with the same or lower RTT counts

```
distribution-generic (client -> server), single streaming format:
-> SETUP
-> SUBSCRIBE id=1 name=catalog
<- SETUP
<- OBJECT id=1
-> SUBSCRIBE id=2 name=video
-> SUBSCRIBE id=3 name=audio
<- OBJECT id=2
<- OBJECT id=3
(2 rtts instead of 3)
```

In the rare case where a publisher wants to output two streaming formats simultaneously, the primary catalog would reference two other tracks which are themselves catalogs. It would look like this

```
distribution-generic (client -> server):
-> SETUP
-> SUBSCRIBE id=1 name=catalog
<- SETUP
<- OBJECT id=1
-> SUBSCRIBE id=2 name=catalog-for-format-A
-> SUBSCRIBE id=3 name=catalog-for-format-B
<- OBJECT id=2
<- OBJECT id=3
-> SUBSCRIBE id=4 name=A-video
-> SUBSCRIBE id=5 name=B-video
<- OBJECT id=4
<- OBJECT id=5
(3 rtts)
```

**Comment by suhasHere** [comment]
Can someone explain what is client and sever in all these cases .

**Comment by suhasHere** [comment]
For my understanding on things below, here are the definitions I will be using

Distribution Scenarios
-----------------------
Endpoint Consumer (client)
Distribution Server/Conference Server (server)

Couple of points or observations :

for end-point subscribers interested in receiving media from a conference or from a distribution server, I think I am leaning towards @wilaw 's proposal :

 - the invariant is, the consumer app knows the catalog trackId and it subscribes to it and rest of the steps from there on flows as defined by the contents  of the catalog
- Also MoQ Transport should not mandate subscribing to the catalog as the first step, since it's application choice. Some applications may choose to get catalog obtained as part of out-of-band step too.

**Comment by suhasHere** [comment]
I do think the contribution proposal is mixing capabilities exchange and catalog exchange all in the announce. Agree with @wilaw  that exposing internals of catalog will eventually cause announce to replicate the entire catalog and which is not useful for relays or will expose privacy sensitive information to them

**Comment by kixelated** [comment]
> Can someone explain what is client and sever in all these cases .

The client sends CONNECT/SETUP and the server replies with CONNECT/SETUP. Otherwise, the protocol is bidirectional and there's no distinction between client or server. 

> By having to ANNOUNCE each track, the client is duplicating what is already inside the catalog. The catalog IS the announcement of what the server is making available for subscription.

I would think of this as a catalog for the generic transport, advertising protocols and entry points. For example, the consumer would have the choice to use the MoQ protocol via the `catalog` track (format `0x1`) and/or subscribe to a chat protocol via the `chat` track (format `0xff54`). 


> This proposal also assumes that "formats" can be scoped to "tracks".

The intention is mainly to announce entry points. Advertising nested tracks, like video/audio in the example, might be useful but it should be optional. It only removes a RTT if the consumer is unequivocally willing to receive an announced track.

But I personally agree with your assessment that an endpoint should parse the media catalog, or delegate to an entity that has, before subscribing to a track.


> I would propose an alternate solution that accommodates the complexity described above and that allows multiple concurrent streaming formats to be offered by the same publisher, with the same or lower RTT counts

There's a few problems with that proposal:

1. There's no way for the consumer to know the fully qualified name of the catalog track. (ex. `webex.com/meeting123/user456/catalog`)
2. There's no way for a publisher to send an auth token per track.

These are the motivations behind PUBLISH in #127. This ANNOUNCE is basically a compromise between the current CATALOG message and the suite of PUBLISH messages.

Personally, I'm a fan of your approach and I did pitch it during the weekly call. It would require scoping track names and authentication to the session. I strongly prefer that over "globally unique" track names and authentication per track.

Also:

3. There's no way to support multiple protocols over the same session. (ex. moq and chat tracks)

I think this can be solved by throwing fields into the SETUP header. For example, `MOQ=3` would flag that the endpoint supports MoQ version 3, and that draft would specify the a consumer should immediately issue `SUBSCRIBE catalog`.

**Comment by wilaw** [comment]
> There's no way for the consumer to know the fully qualified name of the catalog track. (ex. webex.com/meeting123/user456/catalog)

The consumer is given that. They have to be given something to "play". In fact they have to be given two pieces of information 1) the WebTransport or QUIC address to connect to the edge relay and 2) The content "bundle" that they want to play. In the case of WebTransport, these can both be supplied in the same URL. For example

`https://cdn.example.com/accessToken/routingInfo/webex.com/meeting123/user456/catalog`

The first component `cdn.example.com/accessToken/routingInfo/` is used to connect to the edge relay and authenticate the connection. The remainder of the path `webex.com/meeting123/user456/catalog` is the content the client wishes to consume. Since the full path is sent in CONNECT, the server could immediately subscribe the client to the catalog track and send the catalog contents. This removes 1 RTT in the startup. 

> There's no way for a publisher to send an auth token per track.

Couldn't the publisher add an auth token in each object that it sends? We'd want some sort of alias substitution to reduce the wire overhead, but this seems feasible.

**Comment by suhasHere** [comment]
> Couldn't the publisher add an auth token in each object that it sends? We'd want some sort of alias substitution to reduce the wire overhead, but this seems feasible.

PUBLISH_REQUEST or ANNOUNCE (as it is called now) , has auth token in it

**Comment by kixelated** [comment]
Closing my proposals. Discussing the individual issues is more productive.
