### ISSUE TITLE
Proposal: Sync terminology between transport and arch draft

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#157]
PR #156  is updating the transport draft with few terminology , which is fine. However it would be nice to consider the roles/entities terminology defined in https://datatracker.ietf.org/doc/html/draft-nandakumar-moq-arch-00 

It would be good to drive these from security perspective and thus defining roles.

Proposal is to review the terminology in arch-00 spec and either bring in them once we are happy or refer to the arch spec as informative reference in the current spec.

**Comment by afrind** [comment]
For reference, here's the delta between the draft (including 156) and the arch draft:

**Publisher**:
publishes tracks and transmits objects over the network.
vs
publish MoQ Objects belonging to a given track using the MoQ Transport Protocol.

**Subscriber:**
requests tracks and receives objects over the network.
vs
subscribe to receive MoQ Objects corresponding to a track using the MoQ Transport Protocol.

_These seem largely the same, just slightly different word choices._

**Producer** - The initial publisher that encodes tracks and objects.
vs
**Emitter** - Trusted with E2E encryption keys for the media and operate on one or more uncompressed and unencrypted media.  They compress and possibly encrypt and transmit over one or more Data Streams.

**Consumer** - The final subscriber that decodes tracks and objects.
vs
**Receiver** - Trusted with E2E keys and can transform the Encrypted Stream into Encoded Stream and decode the encoded stream to source stream for further consumptions

_For Producer/Emitter and Consumer/Receiver - I'm not highly opinionated and possible bikeshed?  We can vote (hum?!) in the next authors call._

_The main difference is the explicit mention of keys.  Do we need that in the transport draft, or is it sufficient perhaps to say these roles have access to the raw media (not opaque), considering some but not all tracks/objects will be e2e encrypted?_

**Relay**:
subscribes to endpoints and publishes to other endpoints. Relays typically perform deduplication and caching as part of a distributed system.
vs
Trusted with E2E encryption keys.
Entities performing Relay role implement store and forward behavior.  Such entities receives subscriptions and publishes data to the other endpoints that have subscribed to the named data.  They may cache the data as well for optimizing the delivery experience.  Since these entities are not trusted with the E2E keys, they cannot access unencrypted MoQ Object Payload, however they are allowed to access the MoQ Object Header.

_These definitions are largely the same, with some additional examples in the arch version, plus the mention of keys.  The same question about keys applies._

The arch draft has 3 additional roles not mentioned here: Catalog Maker, Key Manager and Media Transformer.  I'm not sure these are needed in the base transport draft now that it has been pared back, but the informative text there is useful for understanding the overall system.

The working group hasn't spent a lot of time reviewing and discussing this architecture draft yet, so I'm wary of including a reference to it at this time may slow transport adoption.  If/when the wg puts it on the path to adoption, then references might be beneficial.

**Comment by suhasHere** [comment]
@afrind agreed.  even some cases where they are not end to end encrypted, the roles does need to talk about it. Relay Role for example are not expected to access/modify raw media or cannot access the raw media. 
I am happy to amend the definitions in the arch spec to reflect non-e2ee cases

Driving the terminology based on the roles will help us to reason about the system as we start add more details.

**Comment by ianswett** [comment]
Consumer seems sensible, would someone like to write a PR?
