### ISSUE TITLE
Section 3.3: Cancellation

### ISSUE THREAD

**Issue by aboba** [moq-wg/moq-transport#202]
Section 3.3 currently says:

"3.3. Cancellation

   A QUIC stream MAY be canceled at any point with an error code.  The
   producer does this via a RESET_STREAM frame while the consumer
   requests cancellation with a STOP_SENDING frame.

   When using order, lower priority streams will be starved during
   congestion, perhaps indefinitely.  These streams will consume
   resources and flow control until they are canceled.  When nearing
   resource limits, an endpoint SHOULD cancel the lowest priority stream
   with error code 0.

   The sender MAY cancel streams in response to congestion.  This can be
   useful when the sender does not support stream prioritization.

   TODO: this section actually describes stream cancellation, not
   session cancellation.  Is this section required, or can it be
   deleted, or added to a new "workflow" section."

[BA]  While the meaning of STOP_SENDING is clear for frame/stream transport
(e.g. stop sending the frame whose transmission is currently in progress),
it is less clear when multiple frames are transported on the same QUIC
stream.

In the case where multiple frames are being transmitted on a stream, the
problem is that STOP_SENDING does not indicate *which* frame the receiver
has given up on.  So how is the sender to interpret it?  For example, after
resetting the stream, does the sender open a new stream?  If so, what
frame(s) are to be transmitted on that new stream?

To address this ambiguity, an application-layer message(s) could be
defined, indicating exactly what the receiver wants the sender to do:

* Stop (re-)transmission of a particular (named) frame.  The existing
stream is reset and a new stream is opened for transmission of subsequent
frames.

* Stop transmission of layer(s). The receiver wishes to the sender to
adjust the operating point, by stopping the transmission of one or more
temporal or spatial layers.  Only the layers that remain will be
transmitted on new stream(s).

Mailing list thread: https://mailarchive.ietf.org/arch/msg/moq/1Zi-IO12grZpEkrYw5c8aXyK9-M/

**Comment by fluffy** [comment]
I think subscribe hints solves the problem of what to start on by saying which object to start the new subscription on. It seems like the solutions to layers would be to put different layers on differenent streams. I would expect different layers to have different priorities which will then mean different streams.

**Comment by ianswett** [comment]
Attendees think there may be valid use cases of STOP_SENDING and RESET and it should not be disallowed.  But typically UNSUBSCRIBE could be used to accomplish the desired behavior.

STOP_SENDING and RESET do not change the state of subscriptions.

**Comment by kixelated** [comment]
Yeah the problem is when there's significant congestion, a player can fall behind on the active subscription. It needs a way of indicating that it is not waiting for group X any longer so the server should not send it, otherwise it's just a waste of bandwidth.

My proposal is to use STOP_SENDING to indicate you don't want something. This does mean that you can't put unrelated objects on the same stream, otherwise you might accidentally reset the wrong objects. 

ex. If I no longer want to receive group X, I STOP_SENDING any QUIC streams containing group X. But that does prohibit sending group Y on the same QUIC stream, so it would prohibit sending the entire track on a single stream.

Alternatively, we could add a STOP_GROUP message or UNSUBSCRIBE_RANGE. We don't want to terminate the subscription.

**Comment by suhasHere** [comment]
Resubscription works fine here. Since a new subscription  is supposed to override an existing subscription from the client, Relay can start sending from the new group.

Also I don't think we need to forfeit track per stream use-case. If someone is using track per stream, they exactly know what properties they are signing up for.

My proposal would be to Subscribe with new start_point

**Comment by kixelated** [comment]
> Resubscription works fine here. Since a new subscription is supposed to override an existing subscription from the client, Relay can start sending from the new group.

Resubscribe only works if the content we don't want is at the head/tail, unless SUBSCRIBE supports ranges instead of a single start/end.

> Also I don't think we need to forfeit track per stream use-case. If someone is using track per stream, they exactly know what properties they are signing up for.

We don't need to forfeit the use-case; the receiver would have to know that it can't cancel streams in this mode. Franky the application has already made a huge mistake if you're encountering congestion while sending all groups over the same stream.

> My proposal would be to Subscribe with new start_point

A UNSUBSCRIBE/SUBSCRIBE message doesn't work because it will cause redelivery of any duplicates. We would have to add RESUBSCRIBE or allow augmenting an existing SUBSCRIBE.

**Comment by aboba** [comment]
@ianswett Agree that STOP_SENDING and RESET_STREAM do not change the state of subscriptions. I'd say the same for CLOSE_STREAM (see: https://datatracker.ietf.org/doc/draft-ietf-quic-reliable-stream-reset/).

**Comment by suhasHere** [comment]
> A UNSUBSCRIBE/SUBSCRIBE message doesn't work because it will cause redelivery of any duplicates. We would have to add RESUBSCRIBE or allow augmenting an existing SUBSCRIBE.

Not with Subscription hints though

**Comment by suhasHere** [comment]
> We don't need to forfeit the use-case; the receiver would have to know that it can't cancel streams in this mode. Franky the application has already made a huge mistake if you're encountering congestion while sending all groups over the same stream.

Yes , its application decision to prefer such a mode. Yes in such cases cancel will cancel the entire stream. But resubscription with a new start_point will help alleviate some.

**Comment by ianswett** [comment]
The group spent time discussing ideas around RESUBSCRIBE/SUBSCRIBE_UPDATE and multiple subscriptions.

@kixelated brought up the fact that a relay may have to issue overlapping subscribes because it doesn't know whether a relative or absolute subscription is earlier.

This needs a new issue for multiple subscriptions and updating subscriptions.
