### ISSUE TITLE
No encoding for GOAWAY

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#213]
The draft doesn't specify how to encode GOAWAY. [See the draft](https://moq-wg.github.io/moq-transport/draft-lcurley-moq-transport.html#name-goaway). At a minimum we need a new connect URL.

**Comment by wilaw** [comment]
I can envisage a number of possible scenarios for GOAWAY:

1. An edge relay that wants you to disconnect from the current relay but then reconnect using the same connect URL as was originally used. This is because DNS will be used to move the client to a different machine. In this case no connect URL is needed. 
2. An edge relay that wants you to disconnect from the current relay but then reconnect using a different connect URL to the same CDN. The CDN knows how to construct its own URLs and hence can generate this connect URL. IN this case  a connect URL should be included with the GOAWAY.
3. An edge relay wants the client to disconnect completely from the CDN and resort to a fail-over CDN. In this case the client would have been provisioned with the fail-over connect URL so no connect URL need be transmitted by the edge server. 

So we have cases where a connect URL is both present and absent with GOAWAY. It should therefore be an optional parameter.

**Comment by fluffy** [comment]
I like the design where the GOAWAY has a URL that tells the client what to try next, it might be the same URL or it might be something different. Seems simple, flexible, and sort of what people expect.

**Comment by hardie** [comment]
On Thu, Jul 27, 2023 at 9:15 PM Cullen Jennings ***@***.***>
wrote:

> I like the design where the GOAWAY has a URL that tells the client what to
> try next, it might be the same URL or it might be something different.
> Seems simple, flexible, and sort of what people expect.
>
2 of  Will's 3 didn't require a connect-URL (one being semantically
"restart" and three being semantically "failover to preconfigured
alternative").  The tricky one is "switch to nominated alternative",
because different CDNs will construct the URLs in ways that vary from each
other, so it will be difficult to ensure that the failover really is to the
same CDN.  Even if you get into the public suffix list or dbound space,
there's going to be some CDN that has constructed itself in a way that
makes that less than obvious from inspection.   Unless you're going to
allow them to nominate any alternative, working through what's allowed here
is going to be tricky.

I'd suggest getting GOAWAY "restart" and GOAWAY "failover" defined now,
since they are easy.  Put GOAWAY "nominated alternative" as a TBD until we
get further along.

Just my two cents as an individual who has been bitten by too-liberal URL
slots (at the extreme the "what to try next" could be a tel URI with the
support number, which is just not on, in my opinion).

Ted

**Comment by fluffy** [comment]
This should be relay to client message

**Comment by fluffy** [comment]
I would like to see the design support a make before break on the new connection in the gracefull move case. It sounded like Luke had ideas for that.
