### ISSUE TITLE
relay forwarding objects

### ISSUE THREAD

**Issue by gwendalsimon** [moq-wg/moq-transport#217]
Line 572. “[Relays] MUST only depend on the fields [for making forwarding decisions]”. 

I am not sure to understand why we would like to restrict here the behavior of Relays to forward the Objects to subscribers.  We can imagine edge processing for the implementation of forwarding decisions based on third-party validation (possibly based on payload). Furthermore, this restriction is not necessary for the norm to be implemented.

**Comment by wilaw** [comment]
The intent of the language here was that relays should only depend on being able to access the headers and not the body of the objects, as the body may be encrypted. However someone may want to build a relay that uses 3rd party logic , or that inspects the payload, in order to make forwarding decisions. I agree that this should not be prohibited by the protocol. We should relax the language to indicate that payloads MAY be encrypted and that relays MUST implement any prioritization instructions carried in the headers. The spec should make no normative statements about how relays make forwarding decisions.

**Comment by kixelated** [comment]
I agree that this is too restrictive and yet unenforceable. 

The intent is to say something like "a router MUST only route based on the IP header". But what about the UDP/TCP header? What about the TLS header? What about the HTTP header? 

I mentioned in the other issue, but we should treat moq-transport as just a layer. There may be other layers stacked on top and which should not be restricted. It's L3/L4/L7 all over again.

**Comment by suhasHere** [comment]
I am always confused when we use the term Relay to mean more than one thing. My thinking so far is, these are the middleboxes who have no role with payload of the MOQ objects. Yes, it cannot be enforced and a implementation can do whatever it wants. However, when we define security properties, we need to be clear on Relay's role. OTOH middleboxes like SFUs, transcoders are more flexible to access payload and may be payload headers  based on the architecture and they fall into different category when defining the security of the system.

**Comment by afrind** [comment]
This is marked not-transport, but the issue was filed against text in moqt, so maybe that's not correct.
