### ISSUE TITLE
Need object delimiters  in the OBJECT header 

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#224]
While implementing stream carrying multiple objects, where the stream was carrying a GOP with multiple encoded frames in it,  the spec currently lacks object delimiters to implement caching at relays and consuming objects at the MOQ consumer library

My proposal is to extend OBJECT Header to have the following strucutre

```
OBJECT Message {
  Track ID (i),
  Group Sequence (i),
  Object Sequence (i),
  Object Send Order (i),
  [Object Length (i)],
  [Last Object Previous Group (i)],
  Object Payload (b),
}

```

* Object Length: Indicates the length of the object, if known
* Last Object Previous Group : Indicates the last object sequence of the previous group and is sent as part of first object in a given group

**Comment by kixelated** [comment]
[Messages already have a length](https://www.ietf.org/archive/id/draft-ietf-moq-transport-00.html#name-messages). Wouldn't the object length be redundant?

Why does a relay need to know the final number of objects in a group? The relay just uses the group/object sequence number to identify active subscriptions (where to forward each object).

Why does a relay need to know the length of individual object anyway? A relay should cache/forward partial objects otherwise it can only introduce latency. Every major HTTP CDN does this already for HTTP chunked-transfer.

It is useful for a decoder to know when a group ends, although you still need some code to check for gaps based on timestamp. A stream per group handles this very cleanly as the stream FIN signals that the group has finished.

**Comment by suhasHere** [comment]
> Why does a relay need to know the final number of objects in a group?

this aids when a new group arrives for  the subscriber to know if it got all the objects from the previous group. 

> [Messages already have a length](https://www.ietf.org/archive/id/draft-ietf-moq-transport-00.html#name-messages). Wouldn't the object length be redundant?

Agreed , I missed it completely.



> A relay should cache/forward partial objects otherwise it can only introduce latency.

Regardless of how the object is encoded or what it encodes, relays should forward objects as they arrive.

**Comment by suhasHere** [comment]
@afrind there are cases when i had tried stream per object. These were in parallel and i had relay peer mesh setup to test out the flows. This causes things to come out of order since some links were congested. Having it part of first object of a new group will make it very clear on the group state . New message might work, but i still see the race happening.

**Comment by kixelated** [comment]
> > Why does a relay need to know the final number of objects in a group?
> 
> this aids when a new group arrives for the subscriber to know if it got all the objects from the previous group.

You wouldn't be able to rely on this message though if multiple groups are lost/starving. For example, your audio decoder is working on group 65 and waiting for the group end signal from group 66. But what if group 67 is sent instead and group 66 is deprioritized or dropped?

A GROUP_END message is a better option, but frankly I think you should just write a pessimistic decoder. Assume the worst case where QUIC streams may get starved for any reason (packet loss, deprioritization, reset, etc). Otherwise, the reliance on this optimistic group size message/parameter is just going to bite you when real issues occur.

**Comment by martinduke** [comment]
This was addressed with Object Status, closing.
