### ISSUE TITLE
Define Upstream and Downstream 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#229]
Luke took some confused text I sent and made it really clear by using upstream and downstream. I think we should add those to are defined terminology.  They would help many places.

**Comment by ianswett** [comment]
Is there a PR for Luke's changes?

**Comment by kixelated** [comment]
There's no PR; it was just some terminology used in an issue. We used it within Twitch but I'm not sure how common it is across the industry.

Data is produced upstream and flows downstream, potentially branching out along the way. I think the branching is meant to symbolize a river but lul they work the other way around (multiple upstream tributaries join together).

The important this is that upstream and downstream changes based on your perspective. Upstream is in the direction of the broadcaster (ex. OBS) and downstream is in the direction of the viewer (ex. VLC). A relay may have multiple downstream subscriptions (fanout), but deduplicates them into one upstream subscription.

**Comment by ianswett** [comment]
My experience with "upstream" and "downstream" is that it can be confusing, like "backend" and "frontend".  I tend to prefer "sender" and "receiver" or "producer" and "consumer" (or "subscriber"), but no term is perfect.

**Comment by fluffy** [comment]
I think we wanted to use produce and consumer for the ends of the chain, but we need something for the next and prev in the chain. The sender and receiver is just too confusing because we send messages both direction even though media on flows one direction.  Not sure what names we need but I do think we should have a clear name for the prev and next hops for media as well as the first and last hop.

**Comment by acbegen** [comment]
> My experience with "upstream" and "downstream" is that it can be confusing

Luke's definition is quite common. And I agree we need terms for next/previous, so I think we can use these.

**Comment by suhasHere** [comment]
How about 
Producer and Consumer for the endpoints that represent media source and sink 

Publisher and subscriber for everything that participates in moqt transport pub/sub protocol

**Comment by wilaw** [comment]
I am tempted to support 'Publisher' and 'Subscriber'  to define the hop-endpoints, however it is quite possible that both end-points publish and subscribe simultaneously, in which case these semantics become murky. For a robust hop end-point description, how about 'client' (the endpoint that initiates the connection) and  'server' (the endpoint that accepts the connection). This is the same definition as offered by RFC9000. 

Upstream and downstream define directions along a distribution system.  Upstream is towards the source. Downstream is away from the source. 

Since distribution is a chain of clients and servers, we still need clear terms to define the original server and the terminal client. Some candidates:

"original server"
- Source publisher 
- Origin publisher
- Origin
- Media source


"terminal client"
- Client Subscriber
- Final client
- Media sink
- End-user
- The Player

**Comment by englishm** [comment]
(Reposting my edited comment because apparently edits don't generate e-mail and I know some people follow these discussions primarily through e-mail.)

~~+1 to the Publisher and Subscriber being per-hop roles~~ Edit: I'm changing my mind on this slightly. Will is right that it can get confusing because an endpoint may assume both roles for the same connection. It's still good to have the Publisher and Subscriber roles to be able to describe the direction of a particular media flow within a single connection, however, it may often be more useful to focus on the Client and Server aspect of how the underlying QUIC connection is initiated.

I agree it would be helpful to have clear terms referring the ultimate endpoints of (a possible chain of relayed) connections.
Perhaps "Origin Publisher" and "End Subscriber" could work for those terms?

+1 to using Upstream to refer to towards or closer to the "Origin Publisher" and Downstream to refer to away from or further from the "Origin Publisher." These relative directional or proximity-describing terms are often useful in describing different scenarios and possible issues.

Edit cont.: I'm realizing that we don't so much need to chose between all of these words as we need to clarify exactly what each pair of words means and in which contexts they apply.

**Comment by ianswett** [comment]
We don't currently use Upstream or Downstream in MOQT, so I'm closing this.

**Comment by fluffy** [comment]
reopen because I still think we need a term along these lines - yes we don't have a term like this today but that is the problem.

**Comment by fluffy** [comment]
I like end subscriber / publisher but not keen on origin. The problem is the term origin in HTTP has so much to do with auth and I would like to point out in HTTP when a client does a HTTP POST, the client that did the post is not the origin. I think origin is going to get complicated when we add auth to MoQT and rather not use that term for something different than how HTTP uses it.

**Comment by fluffy** [comment]
Related to #438
