### ISSUE TITLE
MUST close connection on duplicate parameters

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#247]
Does this apply for duplicate unknown parameters?

If so, it makes for annoying bookkeeping. One has to keep an unbounded data structure of received parameter types,  instead of a handful of bools for the known parameter types.

**Comment by kixelated** [comment]
+1 this was annoying to implement. For each parameter, you have to check if you're already parsed it, including unknown parameters. Then at the end you have to check that all required parameters have been set.

I much prefer how QUIC frames have fixed fields, instead of this optional/unknown parameter scheme.

**Comment by martinduke** [comment]
I will also note that SETUP parameters currently use a SHOULD here, while Track Request parameters use a MUST.
