### ISSUE TITLE
Zero-length messages are foot guns

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#248]
A zero-length message length indicates that the message runs to the end of the stream. It is also possible to have actual zero length messages (in the spec, currently just GOAWAY).

Zero-length messages can only exist at the end of the stream; otherwise, their encoding is ambiguous. (This is fine for GOAWAY, but not in general).

There are several ways to design out of this, which are pretty obvious. We ought to pick one.

**Comment by kixelated** [comment]
Absolutely, I agree.

I want to send each GoP over a QUIC stream. The problem is that the group/object abstraction doesn't let you do that (#244). The closest you can get is to send the entire GoP as an unbounded object, because then a relay is unable to coalesce multiple (unbounded) objects into the same stream.

I think we choose:
- A stream per OBJECT with an unspecified length. QUIC will report the final size via FIN.
- A stream per OBJECT, broken into sized DATA frames like HTTP/3. This allows intermixing messages on the same stream but is transparent to the application.
- A stream per GROUP, broken into sized OBJECT frames. Object boundaries are exposed to the application.

I'm not a fan of the third option. I want to take my 2s media segment and send it over MoQ without parsing/fragmenting at frame boundaries.

**Comment by martinduke** [comment]
My parser would be MUCH simpler if the "end of stream" magic number was UINT62_MAX instead of zero. Of course, this is all inter-related with both @kixelated's concerns and the question as to if we need message length at all except for OBJECT frames.

**Comment by kixelated** [comment]
UINT62_MAX is also a footgun, because you really should throw UnexpectedEOF if a stream FIN truncates a message.

Control messages:
- Don't need a length if we depend on versioning/extensions. ex. QUIC frames.
- Need a length if you want to ignore unknown messages. ex. HTTP/3 frames

Data messages:
- Don't need a length if they run until the end of the stream. ex. one OBJECT per QUIC stream
- Need a length if there's multiple messages per stream. ex. HTTP/3 DATA frames

I'm fine with an explicit length for all messages, but only if group/object abstraction has a tighter coupling with QUIC streams. The only way to transmit a byte stream right now using MoQ is to make a single OBJECT with size=0.

**Comment by kixelated** [comment]
Although I want to avoid implicit sizes like #240. If the last field in a message is a variable size (ex. string), then it still needs to encode its size instead of running until the end of the message. It wastes bytes but that's how TLS works, and it means you don't need separate encoders/decoders for implicit sizes.

**Comment by fluffy** [comment]
I think this subject is misleading. This is not about messages that have no payload which have lots of uses, it seems to be about messages with and indefinte size. 

I can't see any argument for supporting infinite length messages. 

I would argue against them because it will difficult to map into some of the existing ways people want to move data between relays.

**Comment by huitema** [comment]
I think we could take the format of QUIC "stream data" frames as guidance. There is a bit to say "has length" or not. If ahs length, then encode it. If has not, runs through end of QUIC stream.

**Comment by ianswett** [comment]
I thought the intent was because 0 is not a valid length, and it's short (1 byte on the wire), it's a good way to indicate there is not a length?

**Comment by martinduke** [comment]
This is fixed in #255 because zero-length is just a thing for OBJECT. If people want zero payload length for some reason, then we have to use something other than zero

**Comment by martinduke** [comment]
Closed by #255
