### ISSUE TITLE
Subscription requests and buffers

### ISSUE THREAD

**Issue by vasilvv** [moq-wg/moq-transport#260]
Currently, we have GROUP SEQUENCE and OBJECT SEQUENCE parameters that allow subscribing to a track at a specific offset.  As far as I can tell, we do not actually describe what happens when those are not present.  I imagine what most subscribers would want is to receive most recent N groups when they subscribe (for some subscriber-specified N that is determined by how large they want their buffer to be), and we should add a parameter for the said N.

**Comment by suhasHere** [comment]
This is a special case of Subscription hint issue IIUC (#245)

Wondering if we should discuss together

**Comment by afrind** [comment]
>  As far as I can tell, we do not actually describe what happens when those are not present

I hit this in moq-chat when traversing a non-caching relay - a client's subscription to a catalog track came after the most recent group/object was published, so the client didn't get a catalog.  Do *all* relays need to implement caching of some kind in order to satisfy late-comer requests?  Or something else?

**Comment by kixelated** [comment]
I think the default behavior should be to cache/serve the latest group. It's basically required for any sort of catalog. 

But I do think we should support cache-less senders. They can basically only support `waitup` from #245 and will ignore requests to start subscriptions further back.
