### ISSUE TITLE
Rethinking the track-id issue

### ISSUE THREAD

**Issue by huitema** [moq-wg/moq-transport#270]
TL-DR: if we move the Track-ID out of the object field and into a stream or datagram header, we can copy object messages directly to the stream without having to reformat them.

We have been debating solutions to the track-ID problem, with two opposite goals:

- have the server choose the track-id, so the "object" values can be copied as is to the output streams
- have the client choose the track-id, and avoid the race condition between subscribe OK and first object messages.

See Issue #145, PR #258 and #262, and minutes from the October 2023 interim.

The debate is leading to a muddled compromise, in which a default behavior is "client chooses" with some TBD escape condition if the publisher really wants to choose -- which would have to be something better than an error return on every subscribe. I wonder if there is a simple solution.

Big relays with large fan-out do not like having to reformat messages "on the fly". They would prefer being able to simply copy messages from their cache. This is difficult because of the current definition of the OBJECT message:
~~~
OBJECT Message {
  Track ID (i),
  Group Sequence (i),
  Object Sequence (i),
  Object Send Order (i),
  Object Payload Length (i),
  Object Payload (b),
}
~~~
The bits on the wire look like:

| fields | Object Message ID | Track ID | Group, sequence, send order, payload length, object payload |
|------|-----|-----|-----------------|
| On receive | constant | variable length integer | value specific to the object |
| On send | constant | different variable length integer | value specific to the object |

If the track-id is not the same for all receivers, the relays will need for every object to:

- Find out what Track ID to use on the publishing connection, which requires decompressing the Track ID into a Full Track Name on receive, then mapping that Full Track Name to the receiver selected Track ID when publishing,
- Reformat the Object message to incorporate the receiver chosen track ID.
- Send the modified copy to the receiver

Yes, it is possible to use a scatter gather copy, so as to write three segments in place: the constant value message type, the track-id selected by the receiver, and the object specific part of the object message. Implementation would be reasonably simple if the cached value of the track ID was fixed length, e.g. an internal 64 bit identifier of the track. But this scatter-gather would have to be done for each object and each receiver, which is going to cost several instructions per message.

We can observe that in several of the proposed transport encoding, several messages will be sent on the single QUIC stream, and also that a single QUIC stream will typically carry only messages from a single track. Suppose that the stream data start with a "Track-ID" message:
~~~
TRACK-ID Message {
  Track ID (i)
}
~~~
Followed by set of object messages:
~~~
OBJECT Message {
  Group Sequence (i),
  Object Sequence (i),
  Object Send Order (i),
  Object Payload Length (i),
  Object Payload (b),
}
~~~
If the stream only includes objects of the same track, the Track-ID needs to be sent just once. The OBJECT Message would have no variable part, which is useful for caching. The cache itself will have to maintain a relation between cached objects and corresponding track, but it already does, so not a big change. We will save some byte per object message (the track-id varint), at the cost of the TRACK-ID message (one byte message ID plus track-id varint), which means one extra byte if a stream has just one Object, several fewer bytes if the stream has multiple objects. We will also save a couple instructions when pushing messages to streams.

Comments? Was this just the bad-idea fairy putting words in my mouth?

**Comment by afrind** [comment]
Individual comment:

I very much like the separation of hop-by-hop compression information from end-to-end object information - it makes caching a lot clearer.  I also think it's reasonable to restrict one QUIC stream or datagram to at most one track.

Is your proposal to also move to "subscriber picks the ID" along with this proposal? 

> means one extra byte if a stream has just one Object

Since I think we are headed towards a stream identifier at the beginning of every stream to indicate if it is an object stream or the control stream, I think this can be collapsed and not cost a net extra byte.

I'll note that when the publisher is sending stream-per-object, the id rewriting cost is the same as other subscriber chooses proposals.

**Comment by kixelated** [comment]
I would love to see a `STREAM` header for other reasons. I think it's a foot-gun to allow multiple OBJECTs on the same stream that do not share the same track, priority*, and even group (but I know that last one is controversial).

And even if we do allow objects on the same stream with the same value, perhaps you could send another STREAM message. This would avoid encoding redundant values over and over again, or maybe it could even be used as a signal for when the relay should create a new stream.

```
STREAM track=0 group=4 priority=3
OBJECT sequence=0
OBJECT sequence=1
...
OBJECT sequence=58
OBJECT sequence=59
STREAM track=0 group=5 priority=3
OBJECT sequence = 0
OBJECT sequence = 1
...
```

But yeah when there's a single OBJECT per stream, this proposal doesn't really change anything on the wire. But the `scatter gather copy` approach like you described would be built into the protocol which is definitely a little cleaner. I'm all for it.

\* some QUIC implementations support decreasing priorities, but increasing priorities is incompatible with QUIC's flow control.

**Comment by wilaw** [comment]
> The OBJECT Message would have no variable part, which is useful for caching.

Is it useful for caching? I think the opposite might be true.   At a bare minimum, a cached object needs a unique name.   When the trackID is carried in a QUIC stream header, then the interpretation of an OBEJCT, and its position in the cache, is bound to the stream on which it arrived. This has a few drawbacks:
  - its a bit of a layer violation , using the transport protocol to transmit a key attribute of the pub/sub protocol. 
  - it removes the flexibility of mapping OBJECTS to streams. Once you've started a stream, you are constrained as to which objects can be placed inside it. 
 -  consider the case of advanced relays in which the components receiving steams are decoupled from those sending them, or the case where the QUIC transmission is handled via hardware (in the near future) and the stream payload received via API. In these cases the stream header would have to be extracted and routed via some metadata for each object, at which point it might just as well have been in each object. 

With the track ID carried in the OBJECT header, the Object is atomic. This is a useful feature. The atomic OBJECT becomes the common currency between the receive and send sides of a relay. So I think its better to stick with our original concept of a trackID in the OBJECT header and head back to #145 to figure out an efficient way to do that.

**Comment by afrind** [comment]
Individual comment:

> With the track ID carried in the OBJECT header, the Object is atomic.

That's not entirely true, since the track ID today is scoped to a session.  I can't cache an object as {TrackID, GroupNum, ObjNum}, I have to cache it as {Full Track Name, GroupNum, ObjNum}.  So no matter how we pick or transmit the compression identifier for the full track name, the wire representation of the object is not cacheable as is - you have to decompress it first.

> then the interpretation of an OBEJCT, and its position in the cache, is bound to the stream on which it arrived

FWIW this is true for HTTP responses too.  A response doesn't contain the URL.  You use the stream ID to join it with the request to know the name of the thing.

**Comment by kixelated** [comment]
> > then the interpretation of an OBEJCT, and its position in the cache, is bound to the stream on which it arrived
> 
> FWIW this is true for HTTP responses too. A response doesn't contain the URL. You use the stream ID to join it with the request to know the name of the thing.

Yeah, I do want to emphasize that HTTP caches do NOT cache the raw response bytes.

With HTTP/1.1 it's possible to cache the upstream bytes and forward them downstream unmodified. However, this means the relay cannot modify any headers, so it's extremely situational. Even adding a header like `X-Forwarded-For` means you cannot serve the exact same bytes as received. With HTTP/2 and HTTP/3 it's just impossible to cache the raw response.

Instead, a relay will parse the headers into a struct/map and marshal it on a per-connection basis. There's certainly some optimizations you can do, like maybe serializing some of the QPACK headers as literals and sharing them across responses, but it's not advisable since it will hurt compression.

---

I'm proposing something similar for OBJECT. The relay MUST decode the OBJECT headers to function: track ID, group, object, priority, etc. This entire debate revolves around if a relay needs to re-encode the headers, or if it can copy them blindly. The thing is, re-encoding the OBJECT headers is so extremely trivial (they're VarInts) that even the branch miss caused by the slow path (publisher choosing ID) might be more expensive.

The important thing is that the relay does NOT decode the payload; that can be fanned out to multiple streams verbatim. This is what you would store in your cache:

```rust
struct Track {
  name: string,
  objects: Stream<Object>, // a subscribable stream of objects
}

struct Object {
  group: int,
  object: int,
  priority: int,
  payload: Stream<Bytes>, // a subscribable stream of bytes
}
```

Here's the relevant code in [moq-relay](https://github.com/kixelated/moq-rs/blob/main/moq-transport/src/session/publisher.rs#L174). The track ID is replaced in the object header and it's encoded straight to the stream buffer. The object payload is received in chunks, which are zero-copy written to the stream.

**Comment by kixelated** [comment]
Note that with @huitema's proposal, you would split `message::Object` into two separate messages, and the second message _could_ be copied as bytes from the upstream. But it's still probably slower when there's an OBJECT per stream; calling `stream.write()` twice will be more more expensive than re-encoding 3 VarInts.

**Comment by jordicenzano** [comment]
I implemented draft-01 and I have it working now, but I also faced this issue, I realized trackName <-> TrackId relation and how this is specified in the draft-01 created a lot of problems (at least in my implementation)
- If we accept subscribe before announce then we need to rewrite objects (that seems bad)
- Forcing announce first (seems a big constraint)

So, this raised the following question to me: why do we need TrackName? Can we just use trackId everywhere and let catalog have the friendly names?

This is the only variation I have made from draft-01 in my implementation:
- Remove trackName and replace it with trackId
    - Announce has trackId (obviously set in the encoder)
    - Subscribe has trackId (it subscribe to a specific trackId)

**Comment by kixelated** [comment]
> So, this raised the following question to me: why do we need TrackName? Can we just use trackId everywhere and let catalog have the friendly names?

The main reason is wildcard subscriptions. I agree though, I think the track ID within a broadcast should just be an integer referenced in the catalog.

However, you still need a way to distinguish between two different broadcasts. My implementation gets around this by associating a single WebTransport session with a single broadcast, basically using the session layer to tell them apart. There's limitations to this approach, namely that it requires WebTransport pooling for efficiency, but I would very much like to use some form of QUIC session layer to isolate broadcasts anyway (ex. separate control streams).

**Comment by wilaw** [comment]
>  the track ID within a broadcast should just be an integer referenced in the catalog.

But since relays can't read catalogs, we still need a object naming scheme that disambiguates concurrent broadcasts, hence the concept of namespace|name tuple. 

> There's limitations to this approach, namely that it requires WebTransport pooling for efficiency,

Consider the case of an edge relay which must forward thousands of parallel broadcasts to a parent. Requiring each broadcast to be in a unique WebTransport session is more constraining than allowing the relay to shard those broadcasts across streams over as many WebTransport sessions as it needs to optimize performance.

**Comment by suhasHere** [comment]
Conclusion IETF 118
- Track Alias defines compressed Full track name and carried in the object message
- Subscribe ID defines transaction identifier for a given track and there can be more than one Subscribe ID for a given TrackId

**Comment by kixelated** [comment]
> > the track ID within a broadcast should just be an integer referenced in the catalog.
> 
> But since relays can't read catalogs, we still need a object naming scheme that disambiguates concurrent broadcasts, hence the concept of namespace|name tuple.
 
A session ID at the start of each stream identifies the track namespace. Maybe a full writeup would help:

We still have our `ANNOUNCE` message but it contains a `Announce ID: VarInt` and a `Track Namespace: String`. We still have our `ANNOUNCE_OK` or `ANNOUNCE_ERROR` message to accept or reject an announce for the given namespace, and our `UNANNOUNCE` and `ANNOUNCE_RESET` message that immediately closes the announce and any associated subscriptions.

Each QUIC stream would be prefixed with the `Announce ID`, which would be used with a lookup table to get the `Track Namespace` for all messages (control and data) on that stream. The `Track Name` is small since it only needs to be unique per namespace, perhaps even just a VarInt (0=video, 1=audio). You wouldn't need the `Track ID` lookup table any more and you would never rewrite OBJECTs.

There would be one control stream per `ANNOUNCE`. It's kind of annoying to have the server `ANNOUNCE` for distribution, so instead we could have the client create the control channel and send `NAMESPACE role=publisher|subscriber` or something.

I think this is a better design that what we currently have. And it's literally how WebTransport works and what it provides:

- `ANNOUNCE` == `CONNECT` request. 
- `ANNOUNCE_OK` == `CONNECT` response status=200
- `ANNOUNCE_ERROR` == `CONNECT` response status=[345]\d\d
- `UNANNOUNCE` == `RESET_STREAM` on the CONNECT request.
- `ANNOUNCE_RESET` == `STOP_SENDING` on the CONNECT request
- `Announce ID` ==  `Session ID`
- `Track Namespace` == `CONNECT` request path.

> > There's limitations to this approach, namely that it requires WebTransport pooling for efficiency,
> 
> Consider the case of an edge relay which must forward thousands of parallel broadcasts to a parent. Requiring each broadcast to be in a unique WebTransport session is more constraining than allowing the relay to shard those broadcasts across streams over as many WebTransport sessions as it needs to optimize performance.

Without pooling, yeah a QUIC connection per session is expensive to establish. But with pooling, a WebTransport "session" is a VarInt in front of each QUIC stream. There is an additional QUIC stream per session that will just stay open doing nothing.

Why would WebTransport session's layer be any slower than the custom session layer with ANNOUNCE I outlined above?

**Comment by afrind** [comment]
Draft-02 has a mechanism for the publisher to request a different track id, and a object-model mapping to QUIC that borrows ideas from this issue.
