### ISSUE TITLE
GOAWAY stream

### ISSUE THREAD

**Issue by afrind** [moq-wg/moq-transport#29]
What stream does the GOAWAY get sent on?

Can producers send GOAWAY or only consumers?

**Comment by afrind** [comment]
Also what does this mean:

> A server MAY use QUIC load balancing instead of a GOAWAY message.

**Comment by kixelated** [comment]
Good questions.

Right now there's no distinction between control streams and segment streams. In theory the GOAWAY could be sent on any stream. I'm not sure if this is the right behavior.

Only servers can send GOAWAY since the client must issue the WebTransport CONNECT. It doesn't matter if the server is a producer or consumer.

I'll remove that blurb about QUIC load balancing. I was trying to be clever and say that the server can hijack a QUIC connection but that's really not needed in the draft.

**Comment by kixelated** [comment]
Did not mean to close this.

**Comment by suhasHere** [comment]
I think the idea of control stream with GOAWAY message will be useful design here

**Comment by afrind** [comment]
The direction is for a single control stream, so GOAWAY will be there.  There's a separate PR defining GOAWAY, which may or may not address the "Can producers send GOAWAY or only consumers?".  Closing this for now.
