### ISSUE TITLE
Control streams

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#31]
As mentioned in #29, there's currently no distinction between control streams and media streams.

Should we have dedicated control streams? When should these be cached or forwarded by relays?

For example, GOAWAY must NOT be forwarded by a relay, but something like TRACK (does not exist yet) should be forwarded.

**Comment by LPardue** [comment]
This sounds like something worth thinking on and capturing more about in the spec.

**Comment by suhasHere** [comment]
QuicR supports control streams and media streams.
Control Stream is for setup and other control features
Media Streams for delivery media - today it supports QUIC Streams or QUIC Datagrams. 

Regardless having a bidi control stream (QUIC Stream) will come in handy

**Comment by ianswett** [comment]
Discussed today, there was interest in separating today's control messages from media/object streams, but not yet interest in constraining a MoQ session to a single control stream.  Per track and per namespace were both mentioned as reasonable scopes, as well as 1 per session.

There were follow-up questions about Setup messages and version negotiation and how you know which version is in use.

**Comment by kixelated** [comment]
One conclusion from the chat is that QUIC streams MUST NOT contain messages with different priorities. Otherwise, a QUIC library would need the ability to reprioritize a stream at a given byte offset. If control messages are always higher priority than data messages (debated), then separate streams are required.

In my implementation, separate threads process control and data messages separately. Data streams are immediately sent to a media decoder thread (WebWorker) while control streams stay in the main thread. This architecture breaks if control messages and data messages can be interleaved.

---

I think we were in pretty good alignment that there should be control streams. The primary discussion surrounds the scope and number of control streams.

1. control stream per track.
2. control stream per track namespace.
3. control stream per session.

I don't think option 1 is viable for ABR, as you want to coalesce the UNSUBSCRIBE / SUBSCRIBE for separate tracks. For example, (near) simultaneously unsubscribe to 480p and subscribe to 720p. If the tracks are truly independent and can not tolerate head-of-line blocking, perhaps they should use a separate namespace instead?

I think option 2 is acceptable. The goal is to avoid introducing head-of-line blocking for thousands of unrelated track namespaces, but I think this bleeds into the infamous pooling discussion. If pooling is accomplished via multiple sessions like WebTransport, then option 3 also accomplishes that goal.

I'm currently using option 3 since it makes the SETUP marginally handshake easier. Control messages are written immediately after the SETUP message, avoiding the need to buffer messages pending the handshake. It also means you can coordinate subscriptions when tracks are NOT within the same track namespace (ex. ABR across different producers).

**Comment by kixelated** [comment]
Okay so I can't help but start a tiny bit of the POOLING discussion.

My application uses Warp for media and Alan's protocol for chat. Let's assume that I want to use the same QUIC connection for both for efficiency reasons. I would like to design my application into two halves, so one part of the code deals with chat and one part deals with media. I don't want a situation where I have to pass control and data messages between threads. 

It would be really nice if there were two control streams: one to control the chat protocol and one to control the media protocol. This would also be nice for the CDN, as each control streams could be routed to a separate backend/origin. A fatal error (RESET_STREAM) on the chat control stream would not impact the media control stream and vice-versa.

However, this doesn't quite work right now because the can be `track_id` collisions. The chat and media system would need to coordinate to avoid collisions, otherwise IDs need to be rewritten. Any incoming data streams need to be forwarded to the correct component based on this rewrite lookup table.

One way to fix this is to extend all messages to include a `session_id`, where 0=media and 1=chat in this example. Each control stream gets its own ID and OBJECTs would include the ID, avoiding collisions and making it very easy to route within the application and CDN.

(this is WebTransport session pooling)

In fact, now each session could even use a different version of MoQ. This would be super useful when the chat and media backends are running different versions of the protocol. It's why I suggested at the end of the call (@vasilvv) that each control stream contains it's own SETUP handshake.

**Comment by afrind** [comment]
Individual comment:

> One conclusion from the chat is that QUIC streams MUST NOT contain messages with different priorities

Do you mean the "sendOrder" field in OBJECT (section 6.2), or something else?  

I'm not sure normative language is required here, especially if it's based on what current QUIC implementations supports as a prioritization API.  Someday a QUIC implementation could support changing priorities at different offsets for a stream.

As for pooling - WebTransport has taught us that pooling is a huge headache.  I suggest we defer to WebTransport or open multiple QUIC connections rather than trying to define yet another pooling layer in moqt.

**Comment by LPardue** [comment]
>  Someday a QUIC implementation could support changing priorities at different offsets for a stream.

I have a draft in the works to  support doing this for HTTP/3, so it's not far off in my world

**Comment by kixelated** [comment]
> Individual comment:
> 
> > One conclusion from the chat is that QUIC streams MUST NOT contain messages with different priorities
> 
> Do you mean the "sendOrder" field in OBJECT (section 6.2), or something else?
> 
> I'm not sure normative language is required here, especially if it's based on what current QUIC implementations supports as a prioritization API. Someday a QUIC implementation could support changing priorities at different offsets for a stream.

Well, I kinda think the normative language is justified when priority schemes are written on the wire. You're totally right that an implementation could prioritize at byte offsets... but that doesn't mean a relay can support it.

Ugh, I guess we need to discuss if prioritization schemes are negotiated or not. My goal was to require a base scheme (send order) in the transport draft so we could just assume that every MoQ relay will support it, and thus normative language like this is fine. But you're right, new prioritization schemes will absolutely come along and maybe send order should be a guinea pig.

So maybe: if the `extension_send_order` is negotiated, then messages on the same stream MUST use the same `send_order` value. I believe the same is true for @huitema's prioritization scheme.

Either way, point taken and it was a bad argument on my part, and barely even related to the topic of control streams.

> > Someday a QUIC implementation could support changing priorities at different offsets for a stream.
> 
> I have a draft in the works to support doing this for HTTP/3, so it's not far off in my world

Gross but point taken. I assume the priority can only decrease?

**Comment by LPardue** [comment]
> Gross but point taken. I assume the priority can only decrease?

The design doesn't currently implement that constraint, the reason being that an application using HTTP might have have a need to increase the priority of some bytes relative to other streams.

**Comment by suhasHere** [comment]
Going back to the topic of control streams, we need to support both  the following
1. Control stream per track namespace
2. One Control stream for the session - (for setup, termination)

Also i feel the transport draft should have the text for it as well to explain what happens when a control stream for a track namespace is created or reset and how are they related to the data streams carrying the objects.

**Comment by huitema** [comment]
@kixelated mentioned my priority scheme. On the prioritization scheme, my personal thinking evolved as I was studying implementations and consequences. For a while, I did believe that layered encodings would be better implemented by having a single track for the whole media, and having for each object priority fields of some kind indicating the relative urgency of the object. I think now that I was wrong, because it leads to a complex mapping that makes relaying harder, and also because the exact semantic of the "priority field" is too complex to specify in a base protocol.

The transport mappings get much simpler if all objects in a track are treated with the same precedence -- at least within a group. We may debate whether the next group should ever take precedence over the previous one, or never, or only some times. This simplification does force layered encodings to use separate tracks for each layer, and to explain the relation between the tracks as part of the application data. Which amounts to pushing complexity out of the transport and back into the application, which I think is a better tradeoff.

The tradeoff also simplifies the tasks of the control stream, because it only has to manage precedence between streams, not precedence between objects.

**Comment by ianswett** [comment]
Should be fixed with the PR that fixes #138
