### ISSUE TITLE
What if/Why will never deliver an Object/Track

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#345]
If the relay/origin will never be able to fulfill an entire requested SUBSCRIBE, how can it indicate that?  For example, a sequence of relays and the origin may only keep video within 30 seconds of head and discard older content.

As a related question, does the relay need to indicate that there will be gaps in Object or Group IDs so the player doesn't wait for them?

High-Level Q: An object has not been delivered, why?

1. It doesn't exist anymore.
2. It never existed.
3. There wasn't enough bandwidth to send it based on... (ie: priority, the subscriber's latency requirements, etc)
4. It was sent in a stream/datagram by itself and reordered (I think we have this covered?)

**Comment by kixcord** [comment]
Yeah so for the real-time use-case, we don't really need a message because the viewer will skip over any gaps larger than X ms.

But in the low-latency use-case, where we want to buffer content rather than skip, then we do need an explicit signal. Otherwise the viewer will be stuck buffering indefinitely, blocked on a group that will never arrive. The same is true for the start of a subscribe; if I request starting back -5 groups, then the player will buffer until -5 is delivered unless I get an explicit signal otherwise.

**Comment by kixcord** [comment]
> The same is true for the start of a subscribe; if I request starting back -5 groups, then the player will buffer until -5 is delivered unless I get an explicit signal otherwise.

@suhasHere this is also why we need something like #343. The player subscribes starting at -5 and will start playback there (for 10s target latency), buffering until then. However it doesn't know which group is -5, since it receives objects with absolute group IDs instead.

**Comment by wilaw** [comment]
> If the relay/origin will never be able to fulfill an entire requested SUBSCRIBE, how can it indicate that? 

By echoing back the range it can fulfill in SUBSCRIBE_OK response. Let's say the SUBSCRIBE is for groups 10-20, but the origin knows that the DVR window now ends at 15 and it can only return 15-20. For example .

```
SUBSCRIBE
{
 StartGroup 10,
 EndGroup 20
..
}
```

could return 

```
SUBSCRIBE_OK
{
 StartGroup 15,
 EndGroup 20
..
}
```


Some consequences of this
1. A relay can't cache the responses to SUBSCRIBE requests, as they will differ with the time that the request comes in.
2. Relay's need to honor TTL's rigorously. Lets imagine the live stream delivers segments 0-30 and the edge relay caches all of them. A client comes later and asks for 10-20, at the time that the tail of the DVR window is at 15. If the origin is not careful to set the TTL of 0-15 such that they expire from cache , then the edge relay would just server 10-20 from cache which would invalidate the DVR window. Since relays don't read catalogs, the only way to enforce a DVR window for live streams is through TTLs
3. What about gaps in the range? If the origin can return 10-20 but missing 13 and 17, how could it communicate that? One way might be to repeat the tuples of Start and End Group to describe what is available:

```
SUBSCRIBE_OK
{
 StartGroup 10,
 EndGroup 12,
 StartGroup 14,
 EndGroup 16,
 StartGroup 18,
 EndGroup 20,
}
```

or a cleaner syntax like

```
SUBSCRIBE_OK
{
ResponseGroups  [{10,12},{14,16}, {18,20}]
}
```

**Comment by gwendalsimon** [comment]
> > If the relay/origin will never be able to fulfill an entire requested SUBSCRIBE, how can it indicate that?

In Today's world, when the origin has a storage corruption, the "relay" (aka CDN server) does not gracefully notify the client in advance. It replies by a error and the client has to deal with it. 
Not that MoQ should not offer a better process, but just to say that clients are also part of the game. If there is a gap in the flow, then the client can apply the right timers to not get stuck forever.

> 2. Relay's need to honor TTL's rigorously. Lets imagine the live stream delivers segments 0-30 and the edge relay caches all of them. A client comes later and asks for 10-20, at the time that the tail of the DVR window is at 15. If the origin is not careful to set the TTL of 0-15 such that they expire from cache , then the edge relay would just server 10-20 from cache which would invalidate the DVR window. Since relays don't read catalogs, the only way to enforce a DVR window for live streams is through TTLs

Wow, this process seems extremely heavy to me.
First, it would mean that, for every request in the past (positive StartGroup RelativePosition), the relay must check the TTL of all cached segments between StartGroup and largest group ID to check whether all segments will not be expired at the time of their respective playout. It is a lot of processing,
Second, what can the relay do if the segments are not cached (or if some segments are not cached)? Not TTL nor expiration awareness.

Would it be possible to add a metadata in the ANNOUNCEMENT to indicate expiration, and possibly gaps?

**Comment by wilaw** [comment]
> the relay must check the TTL of all cached segments between StartGroup and largest group ID to check whether all segments will not be expired at the time of their respective playout. It is a lot of processing,

Agree. It would be expensive to scan the cache looking for expired objects in the range  _before_ giving the SUBSCRIBE_OK response. The more efficient time to check for expiration is when the server is reading each object in the cache, which it has to do when it serves them out. Perhaps we can send a control message - GROUP #N unavailable - and then skip over the expired objects? We could just skip over them without notifying the client, but then the client would sit there buffering and waiting for the objects it has requested. This means we should invent a means of notifying the client about unavailable groups (due to expiration, object not found etc). 

> what can the relay do if the segments are not cached (or if some segments are not cached)? 

It must do what it always does when it doesn't have something, which is make a request upstream, towards the origin.

**Comment by fluffy** [comment]
Just getting back up to speed on this so I could be missing the key part of this ... I agree we need a way to solve Lukes issue of knowing how -5 corresponds to the live edge but the the rest of this seems unnecessary.  If a client asks for something that is has expired, it just does not get it. I don't think the relay needs to tell clients about gaps, the client can figure that out, and I am sure that I don't want the relay changing what the client asked for.

**Comment by wilaw** [comment]
> If a client asks for something that is has expired, it just does not get it.

Fine, but then the problem becomes the client still thinks it will get it and so it times-out and rebuffers waiting for it instead of taking some other corrective action. How can the client tell the difference between groups that are delayed, versus groups that will never come?

**Comment by suhasHere** [comment]
> How can the client tell the difference between groups that are delayed, versus groups that will never come?

I wonder what parts of this needs to be solved at MOQT layer vs streaming format layer. This seems a requirement specific to certain class of applications.

**Comment by afrind** [comment]
#429 is an attempt to address this

**Comment by martinduke** [comment]
Fixed by the Object Status Field, closing.
