### ISSUE TITLE
Add text to clarify relay behavior when there are multiple announces

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#362]
At interim, to support make before break use-cases, we need to clarify relay behavior when a new announce arrives for existing published.

**Comment by afrind** [comment]
This came up during discussion of #508.  

The current draft is ambiguous whether multiple distinct publishers (not reconnect) can announce the same namespace to a relay.  If that is allowed, should SUBSCRIBE messages be sent to all publishers that have announced that namespace?  What happens if multiple SUBSCRIBE_OKs come back?  Do we need normative text describing how a relay handles all these situations, or is it implementation specific?

Some possible error conditions:

1. Two publishers publisher the same track/group/object with different content
2. One publisher skips an object (perhaps due to a delivery timeout) but another publisher sends it
3. ?
