### ISSUE TITLE
Single Message ID space is unnecessary given messages have context

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#379]
Currently, there's one message section and number space. It's confusing to read and it's not clear what messages can be encoded on a control stream, data stream, or datagram.

### Proposal 1: Annotate Table
| id | name | context |
|-|-|-|
| 0x0 | OBJECT_STREAM | data |
| 0x1 | OBJECT_DATAGRAM | datagram |
| 0x3 | SUBSCRIBE | control |
| 0x4 | SUBSCRIBE_OK | control |
| 0x5 | SUBSCRIBE_ERROR | control |
| 0x6 | ANNOUNCE | control |
| 0x7 | ANNOUNCE_OK | control |
| 0x8 | ANNOUNCE_ERROR | control |
| 0x9 | UNANNOUNCE | control |
| 0xa | UNSUBSCRIBE | control |
| 0xb | SUBSCRIBE_FIN | control |
| 0xc| SUBSCRIBE_RST | control |
| 0x10 | GOAWAY | control |
| 0x40 | CLIENT_SETUP | control |
| 0x41 | SERVER_SETUP | control |
| 0x50 | STREAM_HEADER_TRACK | data |
| 0x51 | STREAM_HEADER_GROUP | data |

### Proposal 2: Split Numberspace
**control messages (bidirectional streams)**
| id | name |
|-|-|
| 0x0 | CLIENT_SETUP |
| 0x1 | SERVER_SETUP |
| 0x3 | SUBSCRIBE |
| 0x4 | SUBSCRIBE_OK |
| 0x5 | SUBSCRIBE_ERROR |
| 0x6 | ANNOUNCE |
| 0x7 | ANNOUNCE_OK |
| 0x8 | ANNOUNCE_ERROR |
| 0x9 | UNANNOUNCE |
| 0xa | UNSUBSCRIBE |
| 0xb | SUBSCRIBE_FIN |
| 0xc| SUBSCRIBE_RST |
| 0x10 | GOAWAY |

**data messages (unidirectional streams)**
| id | name |
|-|-|
| 0x0 | OBJECT_STREAM |
| 0x1 | OBJECT_TRACK |
| 0x2 | OBJECT_GROUP |

**datagram messages:**
| id | name |
|-|-|
| 0x0 | OBJECT_DATAGRAM |

**Comment by suhasHere** [comment]
I like the second proposal better. It is also the way our implementation works where control messages are sent over bidirectional streams and data messages on unidirectional streams. Also its easy to report an error if message are sent on the wrong streams.

**Comment by ianswett** [comment]
I like your proposal, but I don't think this is editorial, since the first and second options wouldn't interop.

**Comment by kixelated** [comment]
Proposal 1 is editorial, while proposal 2 _could_ be editorial. I reflowed the IDs but they could use the current values/names.

**Comment by ianswett** [comment]
How clever, fair point.  It seems like people prefer 2, do you want to write a PR for that?

**Comment by huitema** [comment]
I don't think that we *need* to split the spaces, except maybe for datagrams. With the varint encoding, any number from 0 to 63 encodes on exactly one byte. With proposal #2, we would still have one byte of "type" at the beginning of each unidir stream, because we would need to differentiate between 3 encodings.

Having unique types allows for having just one set of functions to encode or decode messages. If anything, that simplifies writing test code -- for example, we can have a single fuzzer for all message types, which is nice.

Having unique types also provides some forward flexibility, should we ever decide to change the way we send control messages.

What I would like, however, is to simplify the naming. We have currently "proposal 1". @kixelated is proposing a change, so let me propose my own changes: 

Proposal 1 | @kixelated  | @huitema   |
------------|-------------|----------------|
OBJECT_STREAM | OBJECT_STREAM | STREAM_HEADER_OBJECT |
STREAM_HEADER_TRACK | OBJECT_TRACK | STREAM_HEADER_TRACK |
STREAM_HEADER_GROUP | OBJECT_GROUP | STREAM_HEADER_GROUP  |
OBJECT_DATAGRAM | OBJECT_DATAGRAM | DATAGRAM_HEADER |
unnamed | unnamed | SINGLE_OBJECT_HEADER |

The first 3 codes correspond to the beginning of a stream, which is why I like having them qualified as "stream header". Otherwise, we have to remember that a stream starts with a "stream header something", unless it starts via an "object header", which by the way is not quite the same as the unnamed object header used when sending multiple objects in a stream.

As for the datagram header, we have only one value. We could save one byte and make the "key" byte implicit when decoding datagrams.

**Comment by huitema** [comment]
Also, we will have to decide whether the key is a varint or a byte. If we stay with varint, then we will have to specify whether long varint encodings like "0xc000000000000000" are legit.

**Comment by martinduke** [comment]
Fixed by #503, I believe.
