### ISSUE TITLE
Need approaches to Reduce time to join the live media stream

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#39]
We need a way for the player to indicate where in the current ongoing stream to receive the media.

Following 3 options come to mind
1. Start from a previous i-frame ( beginning of the gop)
2. Start from the next i-frame ( wait until the next gop)
3. Start from the current frame ( default )
Last one will not be useful for video probably, but it allows audio frames to rendered from the latest point in time.

This might relate to adding further info to the ``` PLAY ``` message ?

**Comment by VMatrix1900** [comment]
Option 2 will bring more complicity than option 1 because the time of next I-frame is unknown to client. A client almost always want to minimalize the join time. Do we need a mechanism to race between option 1 and option 2? Or we can let sender side decide how to deliver the appropriate frame so that the client can join the stream ASAP.On Nov 12, 2022, at 12:43 PM, Suhas Nandakumar ***@***.***> wrote:﻿
We need a way for the player to indicate where in the current ongoing stream to receive the media.
Following 3 options come to mind

Start from a previous i-frame ( beginning of the gop)
Start from the next i-frame ( wait until the next gop)
Start from the current frame ( default )
Last one will not be useful for video probably, but it allows audio frames to rendered from the latest point in time.

This might relate to adding further info to the PLAY message ?

**Comment by acbegen** [comment]
> * Start from a previous i-frame ( beginning of the gop)
> * Start from the next i-frame ( wait until the next GOP)

RFC 6285 discusses the two options above in detail (the sender determines which option is better). There is also mathematical proof in this [paper](https://ali.begen.net/files/articles/PV12.pdf) showing which idea works better when. The problem space is a bit different but you get the idea.

> * Start from the current frame ( default )

For audio this works. For video, you need an auxiliary stream like we have in HESP.

**Comment by kixelated** [comment]
Ultimately, it depends on the desired user experience. Thus the best option will be to let the viewer/player choose. We could add a "latency hint" but it might not actually be necessary.

Thanks to delivery order and prioritization, the newest GoP will get sent when it's available, taking priority over delivering the rest of the previous GoP. This means the player has the ability to choose between option 1 and 2 by choosing how long to wait. Or the player can start playback immediately with option 1 and skip forward once the next keyframe arrives for option 2.

Also, I don't think audio and video should be aligned. This means you could have a video segment every 2s at keyframe boundaries while you have an audio segment every 200ms or whatever. It introduces some extra overhead, but it enables option 3 either with blank video or desynchronized audio/video.

Or like @acbegen mentioned, we could do something like HESP, where different segments are delivered to different viewers. We must not impose that every viewer gets identical content anyway for stuff like server-side ad insertion.

**Comment by kixelated** [comment]
I think a latency hint makes sense though. Let's assume the CDN has ten 2s segments in the cache, each of which is an entire GoP.

We probably need the latency hint when head-of-line blocking is desired (ascending delivery order). The player will need to specify 6s desired latency to start back three segments in the past. Otherwise the earlier seven segments will get transmitted until the player issues STOP_SENDING for each, both wasting bandwidth and increasing time to video.

The latency hint is optional when live delivery is desired (descending delivery order per GoP). The newest GoP will always get transmitted first until eventually the segments are backfilled to reach the target latency. However if the CDN doesn't know the target latency, then it won't know when to stop transmitting segments, and will have to rely on the player to send STOP_SENDING to avoid wasting bandwidth. The target latency also gives the CDN the potential to temporarily ignore the delivery order and first transmit the segment -6s in the past, then go back to obeying delivery order, which seems like a decent time-to-video optimization for high target latencies.

**Comment by suhasHere** [comment]
At a high level what is needed here is for the player to choose it experience and indicate its preference when joining by specify from where/when it would like to get its media delivered. Latency hint is another useful thing that can be added too.

**Comment by acbegen** [comment]
> Knowing the target latency also gives the CDN the potential to temporarily ignore the delivery order and first transmit the segment -6s in the past, then go back to obeying delivery order, which seems like a custom but decent time-to-video optimization for high target latencies.

We have certain keys in CMCD (and CMSD) to help with this. For example, 'dl' (deadline) CMCD key lets the client tell the CDN when it needs the response. Since client-desired latency is a client-side value, it has to be told to the CDN by each client - if that is an expected feature.

**Comment by afrind** [comment]
SUBSCRIBE now supports starting from the latest GROUP and/or OBJECT.  Is that sufficient?

**Comment by suhasHere** [comment]
Done with group support
