### ISSUE TITLE
No way to prioritize one track above another

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#403]
For low latency audio and video, it's helpful to be able to prioritize one track over another, whether it's audio vs video or one quality of video vs another quality of video.

This prioritization can be very helpful for ABR as well.  One might want to request the next quality up in hopes of upswitching, but continue playing the current quality until it's clear the next quality can be delivered, so the higher quality should be lower priority.

This is somewhat related to #396

**Comment by fluffy** [comment]
100% agree we need to be able to do this.

**Comment by afrind** [comment]
Individual Comment: 

One design consideration here is who can influence the prioritization.  In HTTP both the client and the origin server can send a signal, but the server (or terminating proxy) gets the final say.  

We have sendOrder/priority field which today is 100% publisher controlled.  How would a track level priority construct interact with this?

**Comment by ianswett** [comment]
> Individual Comment:
> 
> One design consideration here is who can influence the prioritization. In HTTP both the client and the origin server can send a signal, but the server (or terminating proxy) gets the final say.
> 
> We have sendOrder/priority field which today is 100% publisher controlled. How would a track level priority construct interact with this?

Based on the use cases I can think of, I was thinking the subscriber requested priority comes first, and then the publisher controlled priority comes second.

**Comment by suhasHere** [comment]
> Based on the use cases I can think of, I was thinking the subscriber requested priority is considered first, and then the publisher controlled priority is considered.

An application (producer + consumer) needs to be aware of relative priorities between the tracks. Say a streaming application that has 4k more important than 1080p.  Catalog would need to identify priorities as defined by the application and the producer delivers them per that. 

Can we subscriber re-oder the priority ? I wonder , if the consumer application is hosted by the same provider of the streaming application, then i don't know why would they have to have a nerd knob in the application to change it for one consumer vs the other ? 

On the point of ABR,  if its the consumer making the choice of what it needs next based on its read of the network, then it will un-subscribe/pause and subscribe to the right track. This is per-subscriber local decision and not related to priorities IIUC.

**Comment by vasilvv** [comment]
I don't think that any scheme other than "subscriber chooses" could really work for priorities between tracks.  The reason for that is that a single connection can have multiple tracks from different publishers, thus the publishers don't really have any reliable way of knowing how to set those priorities with respect to other potential publishers.

So I imagine this would work something like this:
1. Publisher uses the catalog to indicate how it thinks the tracks should be prioritized within the catalog.
2. Subscriber reads those, potentially combines them with relative priorities of the catalogs themselves (alternatively, uses its own application knowledge to adjust things).
3. Subscriber sends SUBSCRIBE messages to the relay with the priorities.

You're correct that this does leave priorities on other hops underdetermined.  That is a bit unfortunate, but I am not sure how much of an issue it is in practice.

**Comment by wilaw** [comment]
> You're correct that this does leave priorities on other hops underdetermined. That is a bit unfortunate, but I am not sure how much of an issue it is in practice.

I agree that this will not be an issue in practice, for several reasons:
1. The relay network (CDN) is built to have good intra-network connectivity and capacity, along with intelligent routing around problems, so the chance of congestion is much smaller than over the last-mile.
2. In the case that congestion still occurs, the relays would likely apply fair-share (equal) priority between forwarded tracks.
3. An advanced relay network would still have the option to sample client priorities and use that to prioritize internal traffic. It might chose to do that in order to offer a more competitive SLA than other relay networks. My gut feel is that the overhead to do this, especially over thousands of concurrent tracks, is of little benefit to the end-clients, but our spec design could still allow it.

**Comment by vasilvv** [comment]
And on ingestion side, the publisher can prioritize the things on the send side without changing anything on the wire (assuming the relay would subscribe without priorities upfront).

**Comment by suhasHere** [comment]
> The reason for that is that a single connection can have multiple tracks from different publishers, thus the publishers don't really have any reliable way of knowing how to set those priorities with respect to other potential publishers.

@vasilvv  I am trying to better understand the application model in this case. Does all these publishers are served by the same application (a given broadcast with multiple publishers / a given multi-party conference / a given multi-party chat session)  or they can be disparate applications that are combined into set of tracks for a given subscriber ?

**Comment by afrind** [comment]
Individual Comment:

As someone who has extensively deployed HTTP priorities through multiple layers of relays (proxies) with measurable user experience wins, I'll say that giving all resources equal priority on relay -> relay and relay -> origin hops has worked out well in practice.  The resource you are prioritizing is the bandwidth at the *bottleneck* link, and this is almost always the last mile.  For sufficiently large networks, there's also no fair way to indicate which "fill" requests should be treated with higher priorities than others.

In contrast, HTTP/2 priorities were designed explicitly so that relays could continue to convey priorities through proxies and the effects were

1) no one ever deployed this
2) the resulting priority scheme was so difficult to manage, it limited application use

These problems resulted in scrapping the scheme after 5 years.

In my view, this experience puts the onus on proponents of prioritizing traffic on backhaul links to bring data showing that this is a practical rather than theoretical constraint.

Further, we should be asking if providing a transport mechanism to *allow* subscribers to express track priority would break an application that wants exclusive publisher control.  I think the answer is no.

Ultimately HTTP priorities evolved to a point where both the client and the server can express a priority signal.  I think moq can follow a similar model, with perhaps stricter guidance about how to merge these signals.

**Comment by LPardue** [comment]
+1 to Alan's comments on bottlenecks and backhaul. 

RFC 9218 had to tread a fine line with its guidance on scheduling and merging. MoQ can do something different but it should all be written out with care.
