### ISSUE TITLE
Reliable Live use-case

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#419]
I'm just going to coin a new term: **reliable live**

It's the use-case when a viewer wants to receive live content but doesn't want to skip anything, as quality is more important than latency. This is an extremely common scenario currently served by HLS/DASH and needs to be supported by MoQ too.

The player implements this by pausing playback (buffering) when the buffer is depleted until it reaches a minimum size. There's also a target latency, which is effectively the buffer size at steady state. The player will not skip over content unless there is an explicit gap. Let's assume fixed group sizes for simplicity. All of the below examples use:
```
group_size=2s
target_buffer=5s
min_buffer=1s
```

## Current Draft
In the current draft, a player start playback by issuing:

```
-> SUBSCRIBE 480p start=-2
<- SUBSCRIBE_OK 480p latest=6835
```

We added #343 so the player would know to start playback at group 6833, buffering any future groups. Unfortunately the player currently doesn't know about gaps, so it could block indefinitely waiting for 6834 (or any group). We need some sort of GROUP_DROPPED message to signal that the player should skip over, much like a DISCONTINUITY in HLS. This has been touted as a feature of FETCH, but it's something we also need for SUBSCRIBE.

The bigger issue is prioritization. If the send_order is decreasing, which is required to allow players to skip over old content, then the buffer will fill _backwards_.

```
-> SUBSCRIBE 480p start=-2
<- SUBSCRIBE_OK 480p latest=6835
<- OBJECT group=6835 send_order=0
<- OBJECT group=6834 send_order=1
<- OBJECT group=6833 send_order=2
```

Playback is blocked waiting for the first 1s of group 6833 but we receive newer groups first in their entirety, including possibly some of 6836 as it starts being generated. We will eventually be able to play this data, but this will dramatically increase startup and buffering time. This is also a problem for DVR, as the prioritization required for live does not make sense for VOD.

The broadcaster could remedy this by baking in head-of-line blocking into send_order but I don't want to do that. A participant on a conference stage may want interactive latency, while a viewer may want high quality (HoLB) instead. A viewer on a TV will want high quality, while a viewer using an interactive application will want low latency. It's not the end of the world but it's a missed opportunity.

The other option is to fetch each group one at a time like HLS/DASH:
```
-> SUBSCRIBE 480p start=-2 end=-1
<- SUBSCRIBE_OK 480p latest=6835
<- OBJECT group=6833
<- SUBSCRIBE_DONE 480p
-> SUBSCRIBE 480p start=6834 end=6835
<- SUBSCRIBE_OK 480p latest=6835
<- OBJECT group=6834
<- SUBSCRIBE_DONE 480p
-> SUBSCRIBE 480p start=6835 end=6836
<- SUBSCRIBE_OK 480p latest=6836
<- OBJECT group=6835
<- SUBSCRIBE_DONE 480p
```

Yikes, not only is this annoying and inefficient, but it increases latency. That's because the next SUBSCRIBE can only be issued only once the final object in the group has been received, causing an RTT of no network connectivity which of course corresponds with a massive I-frame that needs to be delivered. We can do better.

## Fetch #368 
There are multiple fetch APIs floating around, but the gist is that FETCH returns old content while SUBSCRIBE returns new content. Here's how the player would playback from my understanding:

```
-> SUBSCRIBE timeline
<- SUBSCRIBE_OK timeline
<- OBJECT timeline
-> FETCH 480p start=6833 end=6834
<- FETCH_OK
-> SUBSCRIBE 480p start=6835
<- SUBSCRIBE_OK
```

This is complicated, as it depends on an outside track to determine which group roughly corresponds to ~5s target latency for the initial FETCH. But it's actually wrong.

There's the assumption that SUBSCRIBE can be used once we're caught up to live but that's not true because of the aforementioned prioritization issue; the buffer will be filled backwards during congestion. This won't happen on startup due to FETCH but will still occur afterwards.

Just like in the current draft, you either have to bake head-of-line blocking into send_order, or you need to FETCH one group at a time:

```
-> SUBSCRIBE timeline
<- SUBSCRIBE_OK timeline
<- OBJECT timeline
-> FETCH 480p start=6833 end=6834
<- FETCH_OK 480p latest=6835
<- OBJECT group=6833
-> FETCH 480p start=6834 end=6835
<- FETCH_OK 480p latest=6835
<- OBJECT group=6834
-> FETCH 480p start=6835 end=6836
<- FETCH_OK 480p latest=6836
<- GROUP 6835
```

Or there's a world where you could switch a SUBSCRIBE to FETCH once you learn it's no longer the newest group. This is extra extra gross though.

## SUBSCRIBE ORDER #411 
I recently put forth another proposal to deal with this use-case:

```
-> SUBSCRIBE start=-2 order=ASC
<- SUBSCRIBE_OK latest=6835
<- OBJECT group=6833
<- OBJECT group=6834
<- OBJECT group=6835
```

Note that this is best-effort ordering: the groups are still sent on separate streams. The benefit of this approach is that another viewer could achieve lower latency by using the reverse order. This will let the player drop when the buffer is depleted, rather than buffer:

```
-> SUBSCRIBE start=-2 order=DESC
<- SUBSCRIBE_OK latest=6835
<- OBJECT group=6835
<- OBJECT group=6834
<- OBJECT group=6833
```

The downside of this approach is that a relay has trouble knowing which variant of SUBSCRIBE to send upstream. I would advocate for always sending `order=DESC` if there's competing requests, as that's the more latency sensitive mode, but it's ultimately business logic.

The ability to deliver groups in order is one of the proposed features of FETCH, but I think we make it a flag on SUBSCRIBE instead. So is the ability to detect when a group is dropped, but that too is required for SUBSCRIBE.

**Comment by suhasHere** [comment]
> We added #343 so the player would know to start playback at group 6833,

This isn't true always. #343 says the latest group the cache has seen. It may be 6833/ Again your example assumes the group numbers have certain property , which is fine and works for the case being made. But its an assumption though.

**Comment by suhasHere** [comment]
> We need some sort of GROUP_DROPPED message to signal that the player should skip over, much like a DISCONTINUITY in HLS. This has been touted as a feature of FETCH, but it's something we also need for SUBSCRIBE.
 
From what i understand on Subscribe, Fetch proposal . The fetch proposal has a requirement to go find out gap info for the range requested.   As i mentioned, the data plane needs to carry the information that is useful . I and few others have proposed having a explicit message or a tombstone group marks a gap might be useful regardless fetch/subscribe discussions as one is dealing with control plane and another is data plane. We need to spend sometime on what info we need in dataplane to identify the things that matter and also not overwhelm the system .

**Comment by suhasHere** [comment]
> So is the ability to detect when a group is dropped, but that too is required for SUBSCRIBE.

As mentioned above, this is not a subscribe vs fetch discussion, but rather identify what is needed in the data plane to identify any such information and how to do it.

**Comment by afrind** [comment]
Individual Comment: 

> This isn't true always. #343 says the latest group the cache has seen. It may be 6833/ Again your example assumes the group numbers have certain property , which is fine and works for the case being made. But its an assumption though.

For the current draft, I assumed that if I ask for StartGroup=RelativePrev/2 and SubscribeOK says current group is 10 then I will receive groups starting from 8.  It's fine if the publisher wants to skip groups IDs, but the relay can't know that, so the only predictable relay behavior is to do simple math on group IDs, right?

**Comment by suhasHere** [comment]
> he bigger issue is prioritization. If the send_order is decreasing, which is required to allow players to skip over old content, then the buffer will fill _backwards_.

I will try to stay at high level on the discussion point rather than trying to solve a certain way with a certain API.  These are the points of concern from what I understand 

- Subscribe with N different ways to ask for thigs



> For the current draft, I assumed that if I ask for StartGroup=RelativePrev/2 and SubscribeOK says current group is 10 then I will receive groups starting from 8. It's fine if the publisher wants to skip groups IDs, but the relay can't know that, so the only predictable relay behavior is to do simple math on group IDs, right?

Relays serves what it has. Relay can't make decision on application design , that's brittle.

**Comment by suhasHere** [comment]
> The downside of this approach is that a relay has trouble knowing which variant of SUBSCRIBE to send upstream. I would advocate for always sending `order=DESC` if there's competing requests, as that's the more latency sensitive mode, but it's ultimately business logic.

This is pretty handwavy and might work for some applications and break for some other.  I do see this being useful for last mile and anything but that is pretty murky.

**Comment by suhasHere** [comment]
To summarize , i will stay at high level of requirements and not use APIs as examples
- Subscribe with relative offsets and  N ways to request things has many edges cases and issues as was presented by Ian . This makes it hard to reason especially when there are multiple hops and relays distributed across different latency paths.
-  New subscribe has  clear scope and easy to reason about at any point in the system.
- Fetch has a very clear scope with only absolute ranges and very easy to reason about.

What's is being asked ?
- Identify gaps due to node dropping an entire group. Maybe good to have it in data plane and not tangled with subscribe vs fetch.
- Influence delivery order between the groups( please not i am not using the word priority for a reason). By delivery order i mean oldest group first or newest first group.  I can see why this fits naturally with Fetch as each fetch is an independent request (end to end). For subscribe with dedup , this gets hairy pretty soon.

**Comment by suhasHere** [comment]
> here's the assumption that SUBSCRIBE can be used once we're caught up to live but that's not true because of the aforementioned prioritization issue; the buffer will be filled backwards during congestion.

this isn't true. With nothing said, the objects are sent with new group first. So the receiver will get to live head first ,not the other way around.

**Comment by suhasHere** [comment]
> This is complicated, as it depends on an outside track to determine which group roughly corresponds to ~5s target latency for the initial FETCH. But it's actually wrong.

I am not seeing a reason to use timeline track to achieve the functionality. One can subscribe "last" and get the group and do a fetch to older data based on that + catalog information, if needed. Not saying timeline track is good/bad idea, but the example is misleading IIUC.

**Comment by suhasHere** [comment]
> Unfortunately the player currently doesn't know about gaps, so it could block indefinitely waiting for 6834 (or any group)

I am bit surprised to learn that players wont time out after certain wait time and mark things as missing.

**Comment by fluffy** [comment]
You lost me at the player does not know about gaps. It seems it is playing the data.

**Comment by kixelated** [comment]
> You lost me at the player does not know about gaps. It seems it is playing the data.

With group/object/datagram modes, media will arrive out of order. The goal of the reliable live player is to block awaiting every object to arrive to avoid skipping content. However, it's currently perfectly legal for the upstream to silently drop objects for any reason (ex. congestion). This will cause the reliable live player to deadlock; there's a gap in the media timestamps and it doesn't know that it will never be filled.

One solution is to use a stream per track to implicitly signal drops, assuming group/object IDs must be ascending within a stream. But this just doubles down on head-of-line blocking for everybody.

**Comment by kixelated** [comment]
> > We added #343 so the player would know to start playback at group 6833,
> 
> This isn't true always. #343 says the latest group the cache has seen. It may be 6833/ Again your example assumes the group numbers have certain property , which is fine and works for the case being made. But its an assumption though.

The SUBSCRIBE_OK contains the largest value from cache _or_ the upstream SUBSCRIBE_OK. It was added for this explicit purpose.

I don't understand what you mean about group numbers having a certain property: do you mean that they're sequential? The player needs to know definitively that groups exist since it blocks playback until each one is fully received.

**Comment by kixelated** [comment]
> > This is complicated, as it depends on an outside track to determine which group roughly corresponds to ~5s target latency for the initial FETCH. But it's actually wrong.
> 
> I am not seeing a reason to use timeline track to achieve the functionality. One can subscribe "last" and get the group and do a fetch to older data based on that + catalog information, if needed. Not saying timeline track is good/bad idea, but the example is misleading IIUC.

That's not good enough for higher target latencies. The "last" group will be from 0s-2s ago in this example, but we want to start at least 5s back.

**Comment by kixelated** [comment]
@ianswett or @fluffy  can you give an example of how a reliable live player is supposed to use #421? Did I capture the message flow control and logic correctly?

**Comment by suhasHere** [comment]
> That's not good enough for higher target latencies. The "last" group will be from 0-2s ago in this example, but we want to start at least 5s back.

Can you explain why that doesn't work ?

**Comment by wilaw** [comment]
I have been thinking about use case of reliable live and the (common) requirement to start multiple groups back from the live head in a live stream. The current #421 proposal for SUBSCRIBE and FETCH does not allow this to happen. The reason is that the SUBSCRIBE will return the latest group and future groups and the SUBSCRIBE_OK will inform the client as to the latest group number. However, since group numbers are not predictable, even with that information the player cannot issue a FETCH for the preceding two groups. I can imagine three solutions to this problem:

1. The player has to subscribe to a timeline track before it starts. This gives it information on the history of groups and then it can issue a FETCH and a SUBSCRIBE appropriately.The downsides of this approach are the extra RTT to start and the requirement for an application-level construct (the catalog) to join a transport-level track. At the moqt layer, we should have means to subscribe to a track that is independent of application features. 
2. We constrain GROUP numbers to increment by 1. This allows prior (and future) sequences to be predictable, by both clients and relays . It also implicitly conveys information about missing groups. Downside is we lose the flexibility in group numbering schemes. However, given the predictability that we gain, this may be a desirable trade-off. What is the primary use case for non-unitary increase and can that use-case be satisfied via some other mechanism?
3. We make timelines a native part of moqt. For any track, any subscriber (end-clients and relays) can issue a control message asking for the timeline (i.e sequence of group numbers) of a track along with an optional parameter to limit the length of the response. For example TIMELINE (example.com/1234/bob/video , 5) would return the last 5 groups along with a timestamp to indicate when that snapshot was taken. A relay that had seen the last 5 groups due to an active subscription could give an immediate response. One that hadn't would have to make the same request upstream. A relay receiving multiple requests for 5,3,2 etc _could_ disambiguate them and could coalesce them in to a single TIMELINE request upstream. Real-time clients would never ask for a TIMELINE, because the SUBSCRIBE gives them what they need to start, but "reliable live" players would take advantage of it.

**Comment by kixelated** [comment]
You know, somehow it never occurred to me that group IDs were ordered but not sequential. It's a bit of a strange property and should be explicitly called out in the draft because object IDs are sequential.

Is the idea to use DTS as the group ID? I imagine PTS doesn't work because B-frames.

Either way, like Will said, I don't see how the reliable live case would work without sequences, or a timeline. The player needs some way to perform gap detection to know when to block awaiting network traffic. Timestamps aren't good enough because of encoder stalls; you can't assume a constant frame rate.

The application is allowed to use group sequences if it wants gap detection, like in this reliable live example. The relay doesn't have to do anything special.

**Comment by kixelated** [comment]
> > That's not good enough for higher target latencies. The "last" group will be from 0-2s ago in this example, but we want to start at least 5s back.
> 
> Can you explain why that doesn't work ?

I think we're going in circles, because I'm trying. Can you prescribe how a reliable live application should work based on my examples? A diagram of the message flow would be super helpful.

**Comment by kixelated** [comment]
@ianswett brought up another approach to avoid a timeline. The player could SUBSCRIBE first and use the SUBSCRIBE_OK to FETCH backwards. This adds a round trip, much like the timeline, but it's definitely more generic. 

```
-> SUBSCRIBE 480p
<- SUBSCRIBE_OK start=6835
-> FETCH 480p start=6833 end=6835
<- FETCH_OK
```

However, it's not clear how to prioritize a concurrent FETCH and SUBSCRIBE; in this example we want the FETCH to be higher priority but I can envision use-cases where the opposite is true (ex. cache filling). I'm going to link #411 once again, I think we need a way to specify the priority in the SUBSCRIBE/FETCH message.

```
-> SUBSCRIBE 480p priority=4
<- SUBSCRIBE_OK start=6835
<- OBJECT group_id=6835 <part 1>
-> FETCH 480p start=6833 end=6835 priority=3
<- FETCH_OK
<- OBJECT group_id=6833
<- OBJECT group_id=6834
<- OBJECT group_id=6835 <part 2>
```

But this still falters after the initial FETCH, like the examples above. 

```
-> SUBSCRIBE 480p
-> FETCH start=6833 end=6835
...
<- OBJECT group_id=7012
<- OBJECT group_id=7013
...
(congestion/dead zone)
(player buffers, blocking on 7014)
...
<- OBJECT group_id=7016
<- OBJECT group_id=7015
<- OBJECT group_id=7014
(player unbuffers)
```

The send order causes the buffer to fill backwards, so we're stuck buffering for a longer time. We want the SUBSCRIBE to be in ascending order for reliable live, not just the FETCH.

**Comment by suhasHere** [comment]
> -> SUBSCRIBE 480p
> <- SUBSCRIBE_OK start=6835
> -> FETCH 480p start=6833 end=6835
> <- FETCH_OK

This is the approach I was referring to in https://github.com/moq-wg/moq-transport/issues/419#issuecomment-2005762867

**Comment by fluffy** [comment]
I sent a write related to this to the list at 
https://mailarchive.ietf.org/arch/msg/moq/XZyzQiq67VaBwiTttvXJN7AYuFc/

**Comment by vasilvv** [comment]
> Or there's a world where you could switch a SUBSCRIBE to FETCH once you learn it's no longer the newest group. This is extra extra gross though.

You kind of have to do something like this; or, more specifically, I think the relay would have to cancel your subscribe at some point if you're trying to do Reliable Live, and you get too far behind.  The reason here is that at some point, your client would be so slow that it's more than the TTL window away from the live edge, so all of its requests will become fetches to upstream.

**Comment by kixelated** [comment]
> > Or there's a world where you could switch a SUBSCRIBE to FETCH once you learn it's no longer the newest group. This is extra extra gross though.
> 
> You kind of have to do something like this; or, more specifically, I think the relay would have to cancel your subscribe at some point if you're trying to do Reliable Live, and you get too far behind. The reason here is that at some point, your client would be so slow that it's more than the TTL window away from the live edge, so all of its requests will become fetches to upstream.

In this case, I'm talking about what the player would have to do in order to receive old groups first near the live edge. SUBSCRIBE delivers new groups first, so during congestion the player would have to UNSUBSCRIBE and FETCH latest-1 or something gross.

You're right that the relay will have to perform a semantic FETCH to populate gaps in the cache. It doesn't need to be a separate message type though, since in my opinion reliable live needs SUBSCRIBE functionality that is identical to FETCH, except open ended.

**Comment by afrind** [comment]
Individual Comment:

> You kind of have to do something like this; or, more specifically, I think the relay would have to cancel your subscribe at some point if you're trying to do Reliable Live, and you get too far behind. The reason here is that at some point, your client would be so slow that it's more than the TTL window away from the live edge, so all of its requests will become fetches to upstream.

My idea of how a relay works with SUBSCRIBE is that when an object comes in, the relay adds it to a stream send queue for every subscriber.  QUIC drains the queues as CWND and flow control become available, in priority order.

These queues must have a bound though, and there are a few choices we could make for a reliable live use case:

1. As Victor suggests, the relay ends the subscribe with "too far behind".  The subscriber decides what to do next (maybe switches to a fetch loop).
2. Relay stops queuing new objects for trailing subscribers, and switches to a "fetch on low queue" loop to keep the subscription going for them.  Note the fetch may *not* require an upstream call if the relay still has the next object cached.

I don't like client driven fetch loops, since it sounds like one of the things people dislike about HLS (Will has mentioned this), and seems like the relay ought to be able to handle this for me.  However, if the wg feels like it's the right solution I can live with it.

**Comment by kixelated** [comment]
Well said @afrind. A 3rd option is DROPPED message with a retryable flag, indicating we tried to deliver things in order but the buffer is full.

**Comment by afrind** [comment]
> A 3rd option is DROPPED message with a retryable flag, indicating we tried to deliver things in order but the buffer is full.

Thanks for adding that.  How would a client that wants *everything* handle that message?  Unsubscribe and start a fetch loop?

**Comment by kixelated** [comment]
> > A 3rd option is DROPPED message with a retryable flag, indicating we tried to deliver things in order but the buffer is full.
> 
> Thanks for adding that. How would a client that wants _everything_ handle that message? Unsubscribe and start a fetch loop?

Hmm, well I don't think flow control should cause this behavior because that will be trivial to trigger for any large range. I think it would only happen if an object in the requested range used to exist but has since been permanently dropped. 

ex. Twitch would only serve groups for 30s, after which time we would return a 404. The player would have to skip over the group.

I'm not actually sure when `retryable=true` would make sense. Maybe if the subscriber signaled it's own TTL or maximum latency or something.

**Comment by kixelated** [comment]
I think a subscriber might want everything, but it still has to support being disappointed.

**Comment by afrind** [comment]
Individual Comment:

> I don't think flow control should cause this behavior because that will be trivial to trigger for any large range.

This is a case we should consider.  How do you handle a subscriber who grants a minuscule amount of flow control?

> Basically, a subscriber might want everything, but it still has to support being disappointed and being told "no".

Sure, some services aren't going to have the live content always available, though some might (we do).  A permanently dropped message makes sense, but wondering how to handle the case where the object is still around -- it might even still be cached -- it just couldn't be queued on arrival because the client was too slow.
