### ISSUE TITLE
SUBSCRIBE_DONE final object 

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#456]
Section 6.14 says:

"Final Group: The largest Group ID sent by the publisher in an OBJECT message in this track.

Final Object: The largest Object ID sent by the publisher in an OBJECT message in the Final Group for this track."

Is it for the track, or for the subscribe? 

I support it being for the track, as that requires less publisher bookkeeping. But if it's that, we should probably make it clear that we really mean "for the track", unrelated to whatever was delivered from that subscribe_id.

**Comment by ianswett** [comment]
I believe the intent of this field is to tell the peer what the last Object to expect from a subscription is.

* If a track ends, then that's clearly the last Object produced for the track.
* If the subscription specifies a endpoint, this is likely a bit redundant?
* It seems like UNSUBSCRIBE is the case this is most valuable, because one doesn't know what the final Object is?

I'm not convinced there's a good use case for UNSUBSCRIBE.  Instead one can SUBSCRIBE_UPDATE to an Object either already received or one you expect to receive in the near future.  That provides similar functionality with one fewer mechanism.

If a publisher cancels a SUBSCRIBE, is it useful to have the last Object sent in that message?  As you said, that could require a good bit of publisher bookkeeping and either it ends up being extraordinarily conservative or difficult to track.  It seems better to set the expectation that the subscriber likely won't receive any more data from the subscription.

**Comment by martinduke** [comment]
I don't feel strongly about it, but we should fix the text to say what you intend it to say.

**Comment by ianswett** [comment]
I believe this would be fixed by #609
