### ISSUE TITLE
Support capabilities and separate it from Catalog

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#84]

**Comment by kixelated** [comment]
Do you think capabilities would make more sense in the SETUP message? How would we encode it? (pls don't say SDP)

**Comment by wilaw** [comment]
@suhasHere  - can you provide more context and detail for this issue, specifically around what you mean by "support capabilities"? Are you referring to capabilities of the client to consume the content being broadcast (i.e decode HEVC, render Dolby Atmos etc) or capabilities to understand the catalog format?

**Comment by fluffy** [comment]
Let me try and get the use case here for this bug:

Imagine the client is a very generic MoQ device. It has a camera that can send at H.264 many resolution/framerates. It also has a document/desktop share that can do H.264 and AV1 and high resolutions and range of framerates, It has stereo and mono micrphones etc. It can also display 1 or more stream and do client side composition. ( I'm more or less desicrbin the Cisco Desk Pro sitting on my desk but it could just as well be OBS). 

It is connecting to some service such as twitch/webex. I am assuming that webex will construct a catalog that tells the the client what to publish and what to subscribe to. 

The questions is how does the webex service know enough about the devices capabilities to construct a catalog that makes sense in this case. I think we need to sort out some solution to this.

**Comment by fluffy** [comment]
The type of solution I would favor is client can describe it capabilities in something that looks a lot like a subset of a catalog message.

**Comment by wilaw** [comment]
> am assuming that webex will construct a catalog that tells the the client what to publish and what to subscribe to.
> 
> The questions is how does the webex service know enough about the devices capabilities to construct a catalog that makes sense in this case. I think we need to sort out some solution to this.

I think the answer here is that the client (which knows its own capabilities), is the one responsible for constructing its own catalog. It knows all that it can produce and it puts that in a catalog and sends it to webex. Webex may then forward that unmodified to all subscribers, or it may filter it in order to standardize features (i.e remove AV1 across all publishers). There may be some application business logic around what each Webex publisher must provide, but that would be an out-of-band communication and enforcement that is handled by Webex, not MoQ . I don't think MoQTransport has to build in a complex discovery negotiation in which anonymous publishers can be interrogated by a subscriber.

**Comment by afrind** [comment]
Since we're moving catalog out to https://github.com/wilaw/MoQ, do we still need client capabilities defined in the base protocol?

**Comment by suhasHere** [comment]
we can close this  issue and handle it elsewhere
